encounters_weeping_forest = {
  1: "Group of 1d4 sprites approach the characters: Roll 1d4- 1) seeking aid; 2) wanting to trick the characters and bewitch them; 3) having mistaken them for doing wrong against the forest; 4) are curious about their intent.",
  11: "A forest spirit sits near a lake. The creature resembles a 20’ moose. It is willing to show the way to the lost temple of the Sun God to those who are worthy.",
  13: "10’ x 10’ moving wall of ants that are more intelligent when bound together. The wall can separate to form 2 humanoid shapes.",
  14: "A large hill covered in beautiful wild flowers. It is actually a massive shambling mound.",
  16: "A lamentable unicorn of Hubris is sitting on a small island in the middle of a pond, weeping.",
  22: "A group of fae loyal to the Court of Delirium. The fae may be hostile towards the characters depending on their actions in the forest.",
  25: "2d10 Wretched walking along side a tainted Shambling Mound. Krampus is riding on the back of this pitiful creature eating the remains of a small child.",
  26: "A forest spirit that is 20’ tall. It resembles a: Roll 1d4- 1) bear; 2) moose; 3) mountain lion; 4) raven; 5) snake; 6) badger; 7) eagle; 8) a mix of all 7.",
  28: "A group of 2d6 Eisenbar Paladins fighting against creatures of the forest as they attempt to seek the Well of Unfathomable Knowledge.",
  29: "2d3 giant and 3d3 medium sized spiders.",
  33: "A herd of 2d6 deer. There is a 30% chance they are being stalked by a predator: Roll 1d5- 1) wolves; 2) demon; 3) druid; 4) mountain lion; 5) bear.",
  35: "A group of 2d3 adventures who have all become Lost.",
  37: "A group of 2d4+1 Wretched that are sitting on a slowly revolving gigantic wooden top, giggling maniacally.",
  38: "The mummified remains of a lost caravan. Mummies can only be spotted in the thick foliage on a successful DC 14 Intelligence roll. The mummies remain perfectly still until victims come within 5’.",
  41: "3d3 stirges flying through the trees seeking a fresh meal.",
  46: "4d4 man-sized slugs with 2d8 barbed tentacles with small suckers at the ends moving through the forest, their acidic secretions melting everything they touch so the suckers can digest it.",
  48: "A vampire and 3 thralls from Shadowfall seeking the Well of Unfathomable Knoweldge for Depraved Genieva.",
  49: "Small Wretched fairies cruelly pulling the wings of giant moths, giggling gleefully as they do it.",
  53: "3d5 beastmen wandering through the forest wearing the flesh of various sentient creatures as clothing.",
  55: "A grizzly bear corrupted by the Metalphage.",
  58: "A soaked and water-logged bugbear, with distended stomach that sloshes when the creature moves. Inside its belly is a parasitic water weird that will burst out after the bugbear is reduced to ½ HP and will attempt to shove its way down the throat of another creature.",
  59: "Treant corrupted by the Wretched attempts to stalk and throttle the characters when they make camp.",
  60: "Skeletal hands burst from the ground and attempt to tear apart the characters (movement reduced by half). After 1d3 rounds 3d10 skeletons rise from the earth.",
  63: "Pine treant sitting atop a large bronze colored mushroom. The treant has burls all over its body that resemble creepy smiling faces.",
  64: "Large area of the forest is on fire. There is a 1-in-6 chance that a character will notice a malevolent face in the flames.",
  67: "A nervous-looking merchant is being guided to the Court of Delirium by a group of particularly wild-looking fae.",
  71: "A ragged and fierce-looking druid ambushes the characters, accusing them of harming the forest.",
  72: "A cluster of 3d100 (butterflies during the day, moths at night) float gracefully in the air. After a few seconds all fall down dead and shatter as if made of glass.",
  74: "1d4 large moths flutter at characters from trees, attempt to eat characters' hair, but will go for strong-smelling fruit if a character has that.",
  77: "A wizard has released an enraged fire elemental in the forest.",
  81: "Fae of the Court of Delirium are fighting a group of Wretched (both groups are equal in number and strength).",
  83: "A red stone colossus from the Canyons of the Howling Red Rock that appears to have been dead for several centuries. Forest growth obscures it from view.",
  84: "A meteorite crashes to the ground within 100’ of the characters. The meteorite is made of a durable, yet strong metal. Enough ore can be harvested to make 2d2 suits of armor and 3d3 weapons. If armor is not created, then increase the amount of weapons crafted to 4d4. Increase AC of armor crafted by the meteorite by 1 from the standard equipment lists and decrease Fumble die by one level. Weapons crafted by the meteorite increase damage die one step on the die ladder. There is a 10% chance that a malevolent space entity is on the meteorite that will jump on the back of a target and eat their brain. The target must succeed a DC 20 Fort save to survive. Failure means the target is now under control of the parasite.",
  85: "Group of 2d6 Lost that are severely emaciated and barely alive. There is a 20% chance that these poor souls have items worth value.",
  87: "A satyr with auburn-colored hair wishes to make a trade for the Key of the Lucky Thief (pg 264) in exchange for the characters traveling into the ruins of the Skytower (#85 in Lay of the Land-Weeping Forest of Forgotten Memories) and recover the Saturated Sun Stone.",
  88: "A predator is stalking the party: Roll 1d6- 1) bear; 2) wolverine; 3) mountain lion; 4) 1d3 wolves; 5) a troll; 6) giant spider.",
  92: "The ground in a 5’ x 5’ area is covered by vicious and highly territorial fire ants that are 6” long.",
  94: "A red-haired fae’s head rests on a tree-stump while its body balances atop it. It grins needle-sharp teeth at the characters if they approach.",
  95: "Gigantic spider demon acolyte of the Spider Goddess. The demon will be friendly to any servant of the Spider Goddess or those who exhibit interest in serving its dark master.",
  96: "A forest spirit is being attacked by a band of 2d3 Klind.",
  97: "A giant fae that is made of boulders and dirt sits in the mud, talking to several small blue birds resting in a nest up in a tree.",
  98: "A group of 3d6 fae of the Court of Delirium and He Who Wears the Yowling Crown appear before the characters.",
  99: "A vile naga has taken up home in the forest. The area around her lair is littered with the bones of her victims. The soil and surrounding area is slowly turning into a dank swamp.",
  100: "A gigantic green, yellow, and blue caterpillar rests atop a red and white polka-dotted mushroom, smoking a vibrant purple hookah. Any target that partakes of the hookah must make a DC 14 Fort save. Failure means they become sickened and pass out for 2d4 hours. Success- Roll 1d6: 1) transformed into a giant butterfly (but still with the head of the character) for 2d4 hours; 2) 3d8 edible berries begin growing out of the character’s armpits and nose. Each berry restores 1 HP; 3) Hair turns a color of the rainbow (permanently); 4) Personality increased by 1 (permanently); 5) Intelligence increased by 1 (permanently); 6) vomit a thick silk substance that you can use to coat your body. It will harden in 10 minutes and reduce damage taken by 2 for 2d4 hours before it becomes brittle and flakes off. ",
}
