lay_weeping_forest = {
  1: "Dense foliage and lush greenery. Visibility reduced by 75%.",
  16: "120’ waterfall leads into an immense gully. Targets that view this waterfall must succeed a DC 10 Fort save or will instantly have to pee. For those who fail the roll, make a second save, if the target fails a massive wet stain appears on their pant leg and they will suffer bashfulness, and incur a -2 to all Personality rolls for 1d3 hours.",
  18: "Field of large golden mushrooms of varying heights, from 1”- 5’ high. 20% these mushrooms form a Fairy Ring. Fairy Rings always have 1d4 fae and 2d6 sprites lurking about to commit mischief.",
  21: "A field has been turned into a graveyard for all the downed trees of the forest. The trees are stacked 50’ high. A naked dryad stands on one, 20’ up the stack",
  26: "A rusted gate bars entry to an ancient and weathered crypt.",
  28: "All the trees in this area are gnarled and twisted with black bark. The ground is soft and the sweet scent of decay permeates the air.",
  30: "An intricately crafted stone monument rests in an eerily silent field. Even birds will not come near this area.",
  31: "A crag leads down to a huge expanse of caves filled with mineral deposits and large chiming crystals. There is a 50% chance that seven creepy little men will be down there mining the deposits.",
  33: "Village of people that the Court of Delirium have been allowed to make their home here, most are outlaws or exiles from the various nations. All are immune to the forest's effects while under the protection of the Court.",
  35: "Glade of soft moss and flowers. In the center of the glade is a marble altar; the altar is held up by four exquisitely carved statues. The left corners are held up by two satyrs and the right by two beautiful women. All have looks of great sadness on their face. The horn of a unicorn floats 4” above the altar.",
  36: "A 25’ L, 7’ H, 7’ W block of living flesh of those captured by the fae who have wronged or mistreated the forest and its creatures.",
  37: "Stone pillars form a perfect circle around a hot spring. Those that are welcomed by the fae may bathe in these water and are healed of any aliment. Those that are hostile to the fae will be cursed and gain 2 Greater Corruptions (no save).",
  41: "An area of trees with humanoid faces. They are willing to talk to any who have not brought harm to the forest. Their roots lash out at those who mean them harm.",
  42: "2d4 houses that have been built in the trunks of large trees, home to a small village of a group of anthropomorphized animals.",
  46: "A stream that flows gently through the woods; small amounts of gold are deposited in the waterbed. Successful Int checks will yield 2d14 GP worth of gold per hour.",
  51: "A small lake filled with massive lily pads. Frog-man village built around the lake’s edge.",
  56: "Two small ponds separated by a wooden bridge, the water flows over the bridge from one pond to the other in a swirling arc.",
  58: "A small grove of trees that are sentient. All ooze a strange green mist that causes all who breathe it to become calm and relaxed (no save). They move around when bored.",
  61: "Massive waterfall and turbulent stream. Water Weird lurking in the rapids.",
  63: "10’ ivory tower. Inside the tower is 10x larger that what it appears on the outside.",
  64: "Cave that is home to a massive angry nature spirit. The spirit has thorny vines for feet/paws, body of a mountain lion, the head of a bear, and antlers of a moose.",
  66: "Ruins of a Fairweather fort that was retaken by the forest after the army disrespected their agreement with the Court of Delirium.",
  68: "The ground is covered in bulbous knotted plant growths. Slicing these open reveals a sweet-smelling and invigorating sap (those who drink the sap are healed for 2d8 HP, loses healing properties after 1 min of being exposed to the air).",
  69: "Area of trees with large burls on their bark. The burls are covered in orange succulent fruit.",
  72: "Massive tree fort built over 200 years ago. This fort is home to a group of rambunctious children that never seem to age.",
  75: "Ferns growing in large concentration. Close inspection reveals these plants are made of glass.",
  78: "Altar constructed out of the bones of fallen nature spirits. A sect of radical druid use it as a holy site.",
  79: "Area of the forest has become dank, rotten, and fetid. The Wretched have built a monument to the decay of Hubris.",
  80: "Area that has been undisturbed by sentient life for 1d1000 years. The area is thick with massive spider webs.",
  81: "A massive 340’ black-barked tree. Its sap is a thick sulfuric-smelling tar that the Wretched harvest and consume to grant them visions to talk to the corrupted gods of Hubris.",
  82: "Wide glade of beautiful wild flowers. 2d6 grazing animals are in the field at any time. The flowers, when dried, have alchemical properties. These plants grant +2 to Make Potion (DCC, pg 223).",
  84: "Deep crag with waterfall leading into a gully. The water smells like rotten flesh, algae clings to most surfaces. Lizards and snakes hiss and croak. A Wretched village rests atop the crag, while something worse lurks below.",
  85: "Dilapidated remains of the Skytower, an observatory used by the Court of Delirium to understand the passing of the cosmos. The Skytower was desecrated hundreds of years ago by Krampus when the Wretched emerged. The stone displays intricately carved faces of various fae creatures. The forest has reclaimed most of the building, as trees and vines are growing around or through the ruins. A large bronze door, gleaming in the sun beckons the curious.",
  86: "Small stagnant pond that is home to a gigantic turtle. There are 3d100 frogs and toads croaking and moving around the pond.",
  89: "A small grove of trees covered in thick vines. Skeletons of various creatures are wrapped up in the vines. When any creature nears, the vines twitch.",
  90: "The characters stumble across the Court of Delirium.",
  91: "Large hill that has been made into a winding labyrinth by the Twin Sisters of the Waning Moon, two vicious and sadistic night hags.",
  92: "Small village of lesser fae; may be hostile towards characters depending on their actions while in the forest.",
  93: "The Precious Tree of Life, standing at 400’ tall it can be seen even outside of the forest. The Court of Delirium have an outpost of protectors here at all times.",
  94: "A battlefield of a long-forgotten conflict between the Court of Delirium and the Wretched. The bodies of the fallen are perfectly preserved and seem fresh. The wounds on their bodies still ooze blood.",
  97: "A small glade. In the center of the glade is a marble pedestal with a single red apple resting atop it.",
  98: "Grove of trees with purple flowers growing thickly on the trunks. The flowers exude an intoxicating smell that is different to each creature (or character).",
  99: "Remains of an Eisenbar Paladin warband. The forest has torn apart most of the bodies and belongings, however there is a 20% change of finding 2d3 useful items and a 5% chance that there is one lesser magical item.",
  100: "The chicken-legged hut of Baba Yaga can be seen in the distance; the characters feel as though they are being watched.",
}
