encounters_mountains_that_crawl = {
    1: "3d6+4 Malfactorum soldiers.",
    11: "Stone giant raiding party.",
    13: "4d4 Malfactorum troops carried on the back of gargantuan stone beetle.",
    14: "3d3 Malfactorum Fire Beetle Guards riding giant ants.",
    16: "Traders making their way to: Roll 1d4- Odd) Great Plains of Unbidden Sorrow; Even) The Bogwood Swamp",
    22: "2d8+4 Bandits led by crazed and mutated wizard. 251d4 Malfactorum infected by Metalphage (pg 308).",
    26: "3 Malfactorum scouts flying on bloated bumblebees",
    28: "1d4 murdered miners turned into undead (roll for appearance and powers- DCC, pg 381).",
    29: "2d8 Malfactorum building a nursery from a secreted mucous substance and captured miners.",
    33: "1d6 stone giants controlled by brain grubs.",
    35: "1d3 giant spiders",
    37: "Enclave of fire giants.",
    38: "2d10 miners fighting Malfactorum (Malfactorum numbers are double that rolled for miners).",
    41: "2d2 Malfactorum stone shapers.",
    46: "Rock golem carved to resemble a minotaur.",
    48: "Wyvern feasting on a pile of various dead things.",
    49: "Gnoll slavers traveling between the Great Plains of Unbidden Sorrow and the Bogwood Swamp.",
    53: "Jellyfish-like creatures that float in air and eat brains.",
    55: "Harpies in abandoned Malfactorum caves.",
    58: "Skeletal Gun Runners of the Floating Island of Terror moving between Fairweather and the Bogwood Swamp.",
    59: "A roc resting on a mountain peak.",
    60: "Enraged earth elemental that is causing a massive sinkhole to form.",
    63: "Gargantuan stone beetle. There is a 30% chance there are 2d8 Malfactorum riding on the beetle’s back.",
    64: "2d4 acid slugs.",
    67: "3d4+3 troops from Fairweather attemping to fight the Malfactorum.",
    71: "Roving living nightmare of terrified dying child.",
    72: "Several humans and stone giants glued to rock face. Malfactorum are shoving larva down their throats to allow their young to gestate.",
    74: "Half-eaten stone giant corpse with gigantic maggots inside it. The maggots control the corpse and use it to attack.",
    77: "Bizarre creatures that look like sticks and hunger for magic. Each attack by these creatures causes any caster (even divine) to be unable to cast 1 spell (starting with highest level) for 24 hours.",
    81: "Extremely obese stone giant whose belly button has become a swirling vortex; to get sucked in is to simply cease to exist.",
    83: "A large face etched in the mountain that begins singing when anyone gets near it. After the large face answers a question, the person can only converse in song for 2d4 hours.",
    84: "Creature with overlarge head and bulging eyes. The creature’s touch melts metal.",
    85: "Thousands of tiny insects that form a hive-mind and can join together into any shape, granting them telepathic communication with other beings.",
    87: "Thick purple miasma of utterly-crushing despair and agony.",
    88: "Bandits fleeing from gargantuan stone beetle.",
    92: "Animated skeletons trapped in rusted spiked cages.",
    94: "Guardian Naga desires to discuss mysteries of the world.",
    95: "A xorn balancing on a small pyramid, reciting past events of characters in bored sing-song voice.",
    96: "A dismantled murder machine. Inside its chest is a locked and trapped tube with a message inside.",
    97: "2d3 miners fighting four comrades that have brain grubs burrowed into their foreheads.",
    98: "Overturned wagon, goods spilled everywhere, 3d6 travelers in circle around it, facing away from the mess, completely unmoving.",
    99: "An old hag wearing a dress made of the faces of many beautiful women that have been stitched together. She offers a map to vast riches for another beautiful woman’s face.",
    100: "Queen of the Malfactorum and 4d4 elite Malfactorum Fire Beetle guards and 2d8+10 Malfactorum warriors.",
}
