lay_mountains_that_crawl = {
    1: "Twisted craggy fissures, canyons, and pitted rock face.",
    16: "The rock face changes from red to sky blue, which glows and hums softly at night.",
    18: "Ancient carvings on the rock face. If blood is thrown on the carvings, they will speak of the ancient traditions of the stone giants.",
    21: "Fissure leading down into the depths of Hubris.",
    26: "The ground and walls are covered in a purple flesh-like substance that is extremely sticky. Watching it reveals movement underneath. Cutting it open causes 3d100 large maggots to burst out.",
    28: "Small craggy pass filled with floating pink bubbles that are highly acidic.",
    30: "Gargantuan stone beetle that has been petrified and is now being delved out by stone giants for use as a fort.",
    31: "4d10 fleshy pulsating sacks clinging to rock face. Cutting them open causes a deluge of honey and a shriveled Mal- factorum infant in larval state to spill out.",
    33: "Abandoned stone giant camp, signs of battle, death and horror mar the landscape.",
    35: "Pile of bloated stone giant corpses, now Malfactorum nursery. Always 2d24 Malfactorum present.",
    36: "A twisted peak that has craggy holes. Wind blows through the holes, creating a high-pitched whistling sound, mak- ing hearing anything nearly impossible.",
    37: "Malfactorum camp, several captured miners and 2 stone giants held here.",
    41: "Large temple cut into the rock face. Several dead Malfactorum and stone giants.",
    42: "Active mine that is now used as stone giant base. 2d7+1 stone giants present at all times.",
    46: "Area of rock face that has recently been painted showing the history and victory of the Malfactorum over the lesser beings of Hubris.",
    51: "Heavily defended Fairweather outpost resisting Malfactorum siege.",
    56: "Remains of Fairweather outpost. There is 50% chance of mundane supplies being left behind, and 15% chance of the discovery of exceptional items (non-magical).",
    58: "Small lake that glows red at night; infested with radioactive amoebas.",
    61: "Group of traders that became lost in the mountains between the plains and the Bogwood Swamp. They have been partially absorbed into the rock face. Their faces still twitch and show the horror of their last moments.",
    63: "Long-forgotten altar to the Great Slumbering Monolith (pg 207).",
    64: "Small lake with stone ruins can be seen at the bottom.",
    66: "Mossy outcropping with wind-warped tree serving as the hidden base of Fairweather miners. Always 3d8 miners here.",
    68: "Broken chunk of mountain peak that is floating in midair, revolving slowly.",
    69: "Malfactorum slave camp. There are 3d30+10 slaves and 2d30+10 Malfactorum present.",
    72: "Nest of gigantic hornets, stone giants walking around the nest in apathetic trance with large larva eating the flesh off their backs.",
    75: "Small grassy plateau with 2d5 shrubs that colorful berries grow from. The berries of each shrub have various magical properties: Red- blow pink bubbles when breathing for 1d4 hours; Blue- Breath is cold, can freeze a glass of water if you blow on it. Effect lasts 1 hour; Orange- An alchemist adds +1d3 to their Make Potion check when they add this to their ingredients (berry must be fresh and only picked within the last 24 hours); Brown- You smell like fecal matter (suffering -4 to Personality rolls), but you aren’t hungry for 24 hours; Plaid- You gain the ability to cast Magic Shield (DCC, pg 146) as if you rolled a 24-27 once within the next 1d6 hours. If you do not cast this spell, you lose the effect. Each bush has 2d3 berries on it at any given time.",
    78: "You stumble across Glarprar- the stone giant capital, home of the king of the stone giants, Dollrum.",
    79: "Hut of an exiled monk of Lucid Dreamers (pg 94). The hut is strangely shaped and morphed from the rock face.",
    80: "Cave that issues gouts of fire and black smoke. The stone giants fear this cave and believe it to be the home to one of the Five Dragons of Hubris.",
    81: "Malfactorum stronghold. There are always 2d100+100 troops present. 25% chance this fort has a gargantuan stone beetle wandering around.",
    82: "Remnants of mining camp. There is a 35% chance of useful gear being found. 50% chance of finding raw ore worth 4d100 gp being found (the weight of the ore is ¼ the worth).",
    84: "Portal of white marble, shimmering with energy in between the arch.",
    85: "Gigantic fissure, chunks of buildings scattered about, thick spider webs all over.",
    86: "Cave littered with various bones and shells of large insects.",
    89: "Gigantic wooden house perched precariously on mountain peak. Inside is an elderly anthropomorphic peacock witch who speaks of everything in past tense. She will speak of the character’s deaths as if they have already happened.",
    90: "The rock face in this canyon is the color of the rainbow… Licking it does nothing, except make you look stupid and it tastes like crap.",
    91: "The rock face is covered in varicose veins, slicing one open and drinking the yellow sap replenishes 4d8 HP, but makes you jaundiced for one month.",
    92: "Pile of human skulls. Eye sockets glow green and they will talk to whoever gets close. They speak of treasures and give dire warnings of the Rotating Tower of the Opalescent Eye.",
    93: "A swirling, massive tornado that hides a pristine mountain lake.",
    94: "Large castle (occupied by: Roll 1d6- 1) Fairweather troops; 2) gnoll slavers; 3) Malfactorum; 4) bandits; 5) Vile Gut Clan goblins; 6) a wyvern.",
    97: "Ancient cave art that actually is a magical trap that turns victim into a(n): Roll 1d8- 1) donkey; 2) turtle; 3) gnoll; 4) Mutant; 5) Ekrask; 6) giant spider; 7) talking cat; 8) old woman.",
    98: "Fissure that crumbles when walked on. The exposed area shows a huge underground city.",
    99: "Large glade with lush plants, few trees, and the wrathful spirits of nature.",
    100: "Palace on the back of a gargantuan stone beetle. Home to the Queen of the Children of Hubris.",
}
