unsettled_encounters = {
    1: "Aoki Apemen are stalking the characters. There is a 25% chance that a witchdoctor (level 1d3 cleric or wizard) is with them.",
    11: "A small gathering of trees, all are lifeless and bare. Wrapped around the tree trunks are vibrantly green vines that pulsating with flashes of light. Skeletons of humanoids and animals are entwined in the vines.",
    13: "A toucan with emerald gems for eyes sits in a tree. It loves talking to strangers and will give the location to an old ruin if treated well.",
    14: "Swarm of extremely carnivorous ants blankets the ground in a 25’ radius.",
    16: "A herd of 5d5 herbivore dinosaurs wanders through the foliage of the forest: Roll 1d4- 1) Triceratops; 2) Ankylosaurus; 3) Stegosaurus; 4) Hadrosaurid.",
    22: "2d4 giant apes are attacking: Roll 1d5- 1) the characters; 2) Aoki apemen; 3) fighting off a Tyrannosaurus Rex; 4) another tribe of giant apes; 5) group of adventurers.",
    25: "An altar of coagulated blood rests on the backs of two living giant apes. Both look as though they are in extreme discomfort.",
    26: "A Tyrannosaurus Rex burst through the trees and attacks the characters.",
    28: "Aoki witch doctor that is casting a ritual that will bring fire and death from the sky onto the frontier town of Razar.",
    29: "A blood slime waits under a rock or recess to strike its next victim.",
    33: "A 15’ long slug with acidic slime that it uses to digest trees and other organic matter. The touch of the slime also has a 30% chance of causing a Minor Corruption (DCC, pg 116) on a failed DC 16 Fort save.",
    35: "3d10 moss-covered zombies wander slowly through the trees.",
    37: "A Tripod from the Metallic Fortress of End Times is rumbling through the forest",
    38: "1d3 white tigers with colorful stripes are resting on a tree while another silently stalks the characters.",
    41: "A group of explorers that have: Roll 1d5- 1) set up camp; 2) been slaughtered by serpent men; 3) cursed by a witch doctor; 4) eaten by Deinonychus; 5) are slowly sinking in quicksand.",
    46: "1d4 Brachiosaurus lumber through the trees, shaking the ground with each step.",
    48: "A flesh golem sewn together from pieces of apemen, giant apes, and other humanoids bursts from the ground and throttles the characters.",
    49: "The animated heads of humanoid victims hover through the air and gleefully look for a victim to torture to death slowly.",
    53: "2d8 serpent men slither through the underbrush, hoping to ambush adventurers that get too close.",
    55: "Brightly-colored florescent snakes light up the forest after nightfall, seeking and chasing down their prey, which are giant fireflies. Torchlight enrages the snakes.",
    58: "A Tyrannosaurus Rex with a head-mounted laser cannon rumbles through the forest.",
    59: "A group of 3d6 Valkyrie huntresses are purging their territory of vile Aoki apemen and serpent men.",
    60: "Pit trap filled with spears, 2d8 damage. In the pit are several severed heads of explorers on pikes. They will talk to those who fall in the pit and survive. If offered something as a present they will reveal locations of ruins and treasures within. Once their secret has been given they turn to ash and disappear.",
    63: "A pack of 3d3 undead Deinonychus reanimated by an Aoki witch doctor.",
    64: "3d5 lizardfolk hunting serpent men. They will be peaceful to characters if left alone. 20% chance one can speak Common and will offer trade/advice.",
    67: "Fire monkeys swing from trees, howling at the characters to distract them from their colony nest.",
    71: "A leopard made of clear crystal stalks prey in the jungle. If killed it will shatter and cause bad luck to the killer (-2d4 Luck permanently).",
    72: "2d2 Aoki apemen are riding on the backs of: Roll 1d4- Odd) Velociraptors; Even) Predodactyls. They carry bows and arrows and have spiked clubs and rocks that they drop on their enemies.",
    74: "A sentient Tyrannosaurus Rex is having tea with a Triceratops, politely discussing carnivorism vs. vegetarianism.",
    77: "Hunting party of peaceful apemen that are tracking a Hadrosaurid.",
    81: "A group of adventurers that are slowly being corrupted and mutated into giant slugs by some horrible spell.",
    83: "Bird of Paradise with overlarge eyes runs across the jungle floor. If the bird is followed it will lead characters to the Waterfall on the Verge, a place occupied by two separate realities.",
    84: "The spirit of a spoiled little girl who was taken into the forest and murdered by her father.",
    85: "Stampede of 3d10 Triceratops.",
    87: "A demon of Realm of Nightmares seeks to awaken its master who has been locked away somewhere in the forest for millennia.",
    88: "A gorgeous mossy glade that is actually 2d100 moss zombies that are lying on the ground.",
    92: "3d4 large blood beetles which are dragging a mangled corpse back to their mound.",
    94: "A rock golem sits on the bloody remains of adventurers who attempted to get into the dungeon it guards.",
    95: "The queen of the Valkyrie rides on the back of an armored Triceratops. She is accompanied by 3d6 huntresses.",
    96: "A human male frozen in a solid block of ice; a look of shock and horror on his face.",
    97: "An enraged treant that seeks to purge the forest of all non-animal life.",
    98: "Large nesting ground for: Roll 1d7- 1) Triceratops; 2) Ankylosaurus; 3) Stegosaurus; 4) Hadrosaurid; 5) serpent men; 6) lizardfolk; 7) Tyrannosaurus Rex.",
    99: "A tar pit which is the prison for a hideous intelligence. The being seeks to escape and will stop at nothing to break free.",
    100: "Large flower with buds that grow 10’ tall in seconds, then open to reveal one of the faces of characters. The plant will then explode and a plant-based copy character will be left in its place, which will attempt to kill the original.",
}
