unsettled_lay = {
    1: "Humid rain forest with thick foliage and lush green trees.",
    16: "Area of the forest that has been burned and a strange glowing rock sits in the center of the devastation.",
    18: "Village of Aoki apemen that are chanting and dancing around a large bonfire. In the center of the fire are four explorers being burned at the stake; a witch doctor chants to the sky.",
    21: "A babbling stream trickling through the forest. Around the stream is: Roll 1d6- 1) large beetles; 2) tufts of soft fur that glows in the dark; 3) a sleeping dinosaur; 4) 2d10 gems scattered around a ripped and bloody bag; 5) piles of humanoid bones; 6) humming mushrooms.",
    26: "A grouping of small trees that encircle a giant tree. The giant tree is an old treant that watches over his little ones.",
    28: "Village of Aoki exiles that are friendly to outsiders and have shirked the teachings of the Eye of the Eclipse.",
    30: "An ancient village that has been abandoned for 1d100+100 years. In the village center a rickety well leads down to the Bleached Catacombs of the Wretched Dreamer.",
    31: "The area of the forest is suffering from intense rains. The ground is soggy and smells sweet from decay. Large mushrooms grow off of rotted trees and drowned carcasses. Movement is reduced by 75%.",
    33: "Large patch of quicksand that extends down for 2d10 feet.",
    35: "An altar that has been created from the heads of exiled Aoki apemen. Each head has had its left eye gouged out and stuffed into its mouth, which has a constant trickle of blood oozing from the pupil.",
    36: "Eight 15’ high boulders have been carved with the faces of the characters. All seem ancient and weathered. If each character touches their own sculpture, the sun is eclipsed for 1d4 years and the Eye of the Eclipse can be seen in its place.",
    37: "A glade and hilly area that is home to a tribe of giant blueback apes.",
    41: "A marble staircase that zigzags up 7 flights to a metal door that is suspended in air. The door leads to the ruins of the Monkey God of Obliteration.",
    42: "25’ high trees with large brown pods that rattle and shake. When characters get near there is a 30% chance they will split open and release a powerful sleeping agent in a 15’ radius.  ",
    46: "Bubbling pit of thick tar. There are several bodies of animals stuck in the pit.",
    51: "Thin spindly trees upon which an intricately built treehouse rests. This is home to an exiled Aoki witchdoctor.",
    56: "Four boulders are stacked one on top of the other. Each boulder has a face of an angry ape carved into it, and they each face a random direction. What happens if the boulders are rotated?",
    58: "A deep ravine with plants that change color depending on the time of the day. All have unique alchemical properties.",
    61: "Cave with aqua blue walls and frigid air. The walls are covered in vibrant neon-colored cave art.",
    63: "Lake of turquoise-colored water. In the lake and around its edges are 3d100 animals that have been turned to brittle stone.",
    64: "A raging river cuts through the forest. There is: Roll 1d4- 1) a village of Aoki apemen; 2) a crumbling ruin of red stone; 3) a small camp of explorers; 4) an unblemished book that is warm to the touch.",
    66: "Seven massive trees that have had a tunnel carved out of the bases of their trunks. Going through the tunnel in a specific order will cause a vortex to open and bring forth visitors from another world.",
    68: " Rolling hills where Aoki apemen bury their dead. Idols and wooden masks can be found throughout the area.",
    69: "Waterfall that leads to a deep and lush ravine.",
    72: "Natural recess in ground that forms an inverted dome. The outside of the recess is lined with slabs of rock jutting up from the ground, almost as if they were teeth…",
    75: "A massive temple that resembles a double helix (like DNA) and has been constructed out of a gold metal that vibrates when touched, rises high into the sky. Adventurers whisper tales of the ancient riches and magical items housed inside.",
    78: "A 55’ tower with gears, pistons, and cogs. The structure is covered with dirt, moss, and vines",
    79: "A large field of round smooth boulders. If the characters explore further they realize the boulders are dinosaur eggs.  The ground suddenly begins to tremble from gigantic footfalls that are coming hurriedly towards the characters.",
    80: "A step pyramid built in honor of the Eye of the Eclipse. At the top a witch doctor cuts the heart from a captured explorer, as Aoki apemen chant and scream. The stairs run red with blood and dark clouds form overhead.",
    81: "Area of bluffs that has been shaped by flooding, high rains, and vicious winds. If one sleeps in the bluffs at night and survives they will wake up refreshed and completely healed when the dawn light touches their face.",
    82: "Area of the forest covered in large mushrooms in assorted colors of gold, black, green, and blue. All the mushrooms emit a flatulent noise when touched and are toxic to those who breathe in the released gas.",
    84: "Area of forest that has been devastated by some disaster. If able to get an aerial view one can glimpse a gargantuan reptilian foot print in the mud.",
    85: "Cave behind a waterfall that leads to old storage house for explorers that died a horrible death 1d20 years ago. Item of interest: Roll 1d5- 1) Witch Doctor’s Mask- the wearer of the mask may attempt to Lay on Hands of those of the same alignment of the mask (chaotic) 3/xday, cast Paralysis (DCC, pg 264) 1x/day, and Snake Charm (DCC, pg 280) 1x/day. Roll 1d20+Personality mod+level (nix level bonus if any alignment other than chaotic); 2) treasure map to an ancient pirate stash in the Bogwood Swamp; 3) Scroll case with 2d3 spells (either cleric or wizard); 4) Chest of 2d100+100 gold; 5) Flute that puts all listeners to sleep for 1d4 days if they fail a DC 14 Will save. Flute can be used 1x/day.",
    86: "The canopy is so thick it blocks out the sun, but at night the trees all close up, as if they were flowers. All the stars seem magnified in the night sky.",
    89: "Clearing of grass and shrubs, in the center of the clearing is a 7’ tall full-length mirror made of silver and gold.",
    90: "Thick white mist permeates the area. Walking through it causes the mist to be disturbed and swirl around; characters will see the shapes of dead loved ones, enemies, and victims.",
    91: "An alabaster altar that emanates a sense of well-being and peace. When touched the altar becomes red hot, burn- ing the victim for 1d6 damage. The target must succeed a DC 18 Fort save or have blood well up from their eyes, mouth, nose, and ears and begin flowing to the altar for 1d4 rounds. Each round the victim loses 1 physical ability point (temporary).",
    92: "A putrid-smelling bog of vile and fetid greenish water. If you fall in the smell will never leave you, no matter how much you wash.",
    93: "An alabaster altar that emanates a sense of well-being and peace. When touched by a lawful character it heals them for 2d6+6 HP and grants a +2 AC bonus for 24 hours. When touched by a neutral character it heals them for 1d6+3 HP and grants a +1 AC bonus for 24 hours. When touched by a chaotic character it deals 1d6+3 damage and invokes a -2 AC penalty for 24 hours.",
    94: "Hills that have been delved out to create a large labyrinth beneath the soil. Home to a tribe of vicious serpent men.",
    97: "A long-forgotten city from an ancient empire that stretches on for several miles. The now-dry canals and structures are overgrown with vegetation, but are well designed and show superior craftsmanship.",
    98: "A grouping of trees that emit a sweet cocoa fragrance. The trees are covered in thousands of biting flies that are digesting the tasty nectar. If the characters can get their hands on the nectar and drink it, it makes them super hyper, increas- ing their pace by 10’ and giving +2 to Reflex saves for 2 hours. After that the consumer crashes for a 1d4 hour nap.",
    99: "What starts as rain quickly becomes a monsoon. Characters must find shelter or be swept away in high winds and torrential downpour.",
    100: "The Ancient Temple of the Sleeping Serpent, which is now home to one of the Five Dragons of Hubris.",
}
