canyons_encounters = {
    1: "2d10 soldiers of Undra scouting out for beastmen or other monsters. There are 1d4 Royal Guards of the Setting Sun accompanying the troops.",
    11: "Roving band of 2d8 beastmen.",
    13: "A woman rises out of the rock floor as though it were water. She stands before the characters, arms spread wide and looks as though she is dripping in gold.",
    14: "Herd of centaurs that are: Roll 1d3 - 1) friendly; 2) hostile; 3) fighting a band of beastmen",
    16: "1d3 cyclops waiting to ambush the characters at the top of a ravine. They will throw boulders at them.",
    22: "2d8 sentient rock people. They are: Roll 1d4 - 1) silly; 2) warriors; 3) one female and the rest are infants; 4) will show the way to their underground rock kingdom to those who are willing to defeat the dreaded “rock eater!”",
    25: "A manticore flies overhead and dives at one of the characters.",
    26: " A caravan is headed to Razar near the Unsettled Expanse to trade goods.",
    28: "A set of huge eyes and a mouth form on the rock face. The features move, swirl, meld, and melt as if only partially in this reality.",
    29: "Band of 5 adventurers exploring the canyons to find riches. All are level 1.",
    33: "A grouping of dead-looking trees. The nest of 3d12 blood harpies.",
    35: "Group of prisoners being forced to build a new fort for Undra. There are 2d20+20 prisoners and half that in guards.  The overseer is a level 1 wizard.",
    37: "A cloud of darkness that smells of sulfur. A chimera emerges from the cloud.",
    38: "2d5 blood harpies attack the group from above.",
    41: "A trap that causes the walls to cave in on the characters. DC 15 Ref save to avoid. 3d6 damage.",
    46: "2d6 prospectors returning from Wrath, the Crystalline Forest with a good haul of crystal from the trees.",
    48: "A minotaur leads a group of 2d16 beastmen on a march against an Undra fort.",
    49: "2d12 soldiers of Undra are being attacked by: Roll 1d5- 1) beastmen (outnumber troops 2-to-1); 2) 3d5 blood harpies; 3) 4 enraged centaurs; 4) a drake; 5) attacking each other, driven mad.",
    53: "A band of 6 explorers heading to Undra after returning from the Unsettled Expanse. They have several strange artifacts that they would be willing to trade.",
    55: "A group of 3 explorers suspended upside down in thick webbing. They were caught by a large rock spider.",
    58: "A floating eyeball drips blood into a large pool of congealed and sweet-smelling blood.",
    59: "Open hole in the ground that seems to be salivating. When characters get too close teeth burst from the sides and tentacles spring from the hole and attempt to drag target into the maw.",
    60: "1d3 rock spiders are hidden in the canyon waiting for easy prey.",
    63: "A cyclops is holding a golden orb that shoots out searing bolts of light at whoever the monster points them at.",
    64: "Beastmen are moving siege engines through the canyons towards Undra.",
    67: "A tribe of centaurs are battling ogres over a strange floating cube.",
    71: "1d3 blood oozes emerge from holes in the canyon wall and pursue the characters.",
    72: "2d2 stone giants punch the wall to make themselves a new cave.",
    74: "A tribe of ogres lead by ogre mage",
    77: "2 hippogriffs protecting their nest.",
    81: " 1d4 sentient rock people being attacked by prospectors, cracked open for their geode centers.",
    83: "A gigantic transient flytrap stays motionless while the party passes by, waiting for the last poor soul to get close.",
    84: "Two golems carved from the red rock block the way through the canyon. Those who attempt to get by are attacked by the large statues.",
    85: "A massive bolt of lightning arches through the sky from Wrath, the Crystalline Forest and strikes the ground in front of the party. 2d4 small electric elementals are released from the blast.",
    87: "A purple worm burrows through the canyon causing tremors and rockslides throughout the region.",
    88: "A trap is set off and releases dried purple fungus powder- causes euphoric feeling mixed with grand hallucinations for 2d10 turns, Fort save DC 15.",
    92: "A small swirling vortex comes towards the characters. It is actually an air elemental searching for its long lost master.",
    94: "A merchant from Undra heading to Razar. He has many interesting things for sale, including a small handheld weapon that fires burning beams of light.",
    95: "A lamentable unicorn of Hubris sits by an emerald lake, weeping.",
    96: " A lamia sits in front of her home on a large boulder, her eyes wide and unblinking, eating the remains of children. If approached or attacked she will pull out her eyes and prophesize a curse upon the characters.",
    98: "A Djinni sits on a rock, angered at being left behind by his companions on the plane of Hubris.",
    99: "A warband of beastmen attacking a small Undra waystation, lead by one of the Four Gorgons of Desire.",
    100: "A colossus stomps past the group, filling their field of view with its gargantuan form. A low rumbling mixed with a strange musical note can be heard from the creature.",
}
