canyon_lay = {
    1: "Red canyons leading to: Roll 1d5- 1) a fertile gully; 2) dried up riverbed; 3) raging river; 4) mud pit; 5) a single golden flower.",
    16: "Area of canyon wall is covered in gorgeous cave art that gives off a sense of foreboding.",
    18: "A small outpost ran by the guards of Undra. There are always 2d10 guards and 2d5 tradesmen at the station. 20% chance of ranking military or nobility at outpost.",
    21: "A gully of lush purple and emerald flowers. At the edge of the gully, crimson water swirls and churns in a lagoon.",
    26: "The canyon walls are made of brittle and sandy sediment. Small thorny cactus grow in the wall cracks.",
    28: "Area of the wall is full of air-breathing coral with sea fans, anemones, and seaweed that float and move as though underwater.",
    30: "The crumbling corpse of a colossus that is being reabsorbed back into the canyon wall.",
    31: "Area of canyons where magic ceases to function for 1d4 days.",
    33: "Intricately carved ruins built into the rock face. The door is carved to resemble the full moon with an enraged face.",
    35: "Small craggy ravine leads to a bronze door with an eagle head knocker.",
    36: "The sun always shines on this portion of the canyons. Those who stay in the area are unable to sleep and become easily dehydrated. Area is filled with lush plants.",
    37: "Rockslide occurs as the characters are walking through. There is a 45% chance that the group will be separated or entombed by the slide and must free themselves.",
    41: "Massive 5,000’ waterfall that leads into a bowl-shaped lagoon. At the bottom of the lagoon is the entrance to the prison of an entombed water demon of envy.",
    42: "The canyon gives way to a flat vista overlooking the other canyons below. There is a rail and a rickety sign reading, “Scenic overlook. Stay away from ledge.”",
    46: "Area is filled with softly glowing orbs that hum when living creatures approach. They are warm to the touch.",
    51: "Old outpost that now serves as a base for beastmen.",
    56: "The canyon walls are porous and a strong whistling draft blows back and forth between them. Hearing is reduced by 75% while in the area.",
    58: "Abandoned Undra outpost that fell during a beastman attack. The spirits of the slaughtered still walk the halls, enraged at their death.",
    61: "The canyon walls are covered in screaming mouths and several explode spewing out red dust into the air.",
    63: "The walls are made of a slimy and wet mucus membrane. If pushed hard enough the wall will give way and allow the character to pass through. They will find themselves within a temple of the Heathen Below.",
    64: "20’ ant hills make traveling through the area difficult. Movement is reduced by 50%. These anthills are long abandoned and there is a 25% chance that they have something of interest hidden within.",
    66: "Rickety wooden staircase leads into the bowels of the earth.",
    68: "Long abandoned fort of black rock that was once home to one of the Cyclops warbands.",
    69: "Ruins set into the wall that have collapsed, but fist-sized objects glitter in the sun.",
    72: "Blue-hued crystals grow out of the canyon walls. These are similar to a phenomenon that occurs in Wrath, the Crystalline Forest. Every turn there is a 3 in 6 chance that a lightning bolt will be unleashed and strike: Roll 1d6- 1) a character; 2) the opposite rock face; 3-5) another crystal formation; 6) arcs up into the sky. Lightning bolt +5 to hit, 2d6 damage. DC 14 Ref save for half damage.",
    75: "Pool of acid green water. Those who touch the water must make a DC 18 Fort save or gain a corruption: Roll 1d3- 1) Minor; 2) Major; 3) Greater.",
    78: "30’ high sculpture of a Cyclops’s face. When the sun hits its eye just right it closes shut and the sculpture's mouth opens, revealing a door to the ruins of Guardian of Time and Space.",
    79: "Ancient portal covered in vines and plants. Runes around the edge of the structure are an ancient language. If properly read it will activate the portal and create a gateway to a lush jungle world.",
    80: "Deep canyon with a gully full of gigantic plants, animals, and insects. All life that has grown or lives in this valley is 4 times larger than normal.",
    81: "Open volcanic chasm that spews hot ash and gas constantly. There is a 2 in 6 chance that it will erupt and shoot hot magma and flaming boulders into the air.",
    82: "Fossils of gigantic prehistoric insects line the rock face.",
    84: "Deep chasm that echoes the last sound that happened in it forever. Staring into the chasm for 1 minute causes a character's eyes to become black wells for 1d4 days, granting darkvision for the duration.",
    85: "Intricate cave art that takes shape and moves when viewed. It shows the group of characters viewing it and foretells of an event that will occur: Roll 1d5-1) calamity; 2) fortune; 3) betrayal; 4) celebration; 5) surprise.",
    86: "Lake filled with chilled salty water. Everything floats on the water, no matter how heavy.",
    89: "Undra fortress that is preparing for an incoming beastman attack.",
    90: "Reactor built into the rock face hisses and rumbles as pistons and gears turn and shoot up blue steam.",
    91: "Field of purple, blue, and red fungus. The fungus becomes brittle and dusty with age. The dust has various effects: Purple- causes euphoric feeling mixed with grand hallucinations for 2d10 turns, DC 15 Fort save; Blue- causes anxiety and fear if inhaled for 2d10 turns, DC 15 Fort save; Red- causes feeling of warmth and flushed cheeks, and changes hair color to red (will regrow normal color) and heals target for 2d4 HP per use; Blue/Red/Purple- when all are mixed together creates a noxious smelling gas that causes all who breathe it to become violently ill and disorientated. DC 18 Fort save or unable to act for 2d10 turns.",
    92: "Part of an ancient galley that looks as though it has been absorbed by the canyon walls.",
    93: "Open fissures in the rock face that ooze stinking yellow pus. Pus is radioactive and can cause mutations. Any target within 30’ must make a DC 18 Fort save. Failure gains a mutation: Roll 1d5- 1-3) cosmetic; 4) power; 5) calamitous.  If in the affected area for more than 1 hour targets start suffering 1d6 permanent Stamina damage (even if passed initial Fort save). Only one mutation per character.",
    94: "Flashflood rips through the canyon; will take trees, plants, rocks, and characters with it.",
    97: "The red canyon gives way to reflective black obsidian. The character’s reflections show the deepest darkest evil within each of them and a feeling of primal elation creeps into their minds. Clerics of good deities feel wrath and anger from their god and lose their abilities until they atone.  ",
    98: "2d4 6’ high human-looking faces have been carved into the canyon walls. They will spring to life when approached and are eager to talk. Each knows an important message about things that have come to pass, things that will come to pass, or things that are too outlandish to ever happen.",
    99: "400’ high bluffs form a crescent moon around a 500’ high spire of marble and turquoise. Large flying creatures can be seen circling the top of the spire.",
    100: "Massive bulge of slick and gooey red rock protruding from the canyon wall. A low grumbling can be heard and the bulge is moving as though something huge is attempting to break free.",
}
