# Generated by Django 3.2.9 on 2021-11-29 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Monster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img_url', models.URLField(blank=True)),
                ('init', models.CharField(max_length=3)),
                ('AC', models.IntegerField()),
                ('HD', models.CharField(max_length=6)),
                ('Act', models.CharField(max_length=10)),
                ('AL', models.CharField(choices=[('L', 'Loyal'), ('C', 'Chaotic'), ('N', 'Neutral')], default='N', max_length=1)),
                ('Atk', models.CharField(blank=True, max_length=100)),
                ('SP', models.TextField(blank=True)),
                ('Spells', models.TextField(blank=True)),
                ('SV', models.CharField(max_length=25)),
                ('description', models.TextField()),
            ],
        ),
    ]
