# Generated by Django 3.2.9 on 2021-11-29 14:12

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('bestiary', '0002_monster_mv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monster',
            name='description',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
