land_of_perpetual_stone_and_mire_encounters = {
    1: "2d4 marauding orcs.",
    11: "Large rock spider with 5d10 babies on its back.",
    13: "Thick fog that holds the consciousness of a cleric of the Terrible Whisper. The cleric gained utter disapproval of his god by burning down a library of ancient and lost knowledge.",
    14: "Large band of Eisenbar paladins and their support marching across the Land of Perpetual Stone and Mire to cleanse the corruption.",
    16: "2d5 members of the Cult of the Molten Raven sitting beneath a tree listening to the garbling of a Rabid Raven.",
    22: "1d8+1 Klind slavers, one is a cleric of Set (lvl 1d3).",
    25: "A sky whale, transformed into an abomination by orcs, drifts in the sky.",
    26: "A living acid cloud is slowly drifting towards the characters.",
    28: "A wyvern is attacking an expedition force from Fairweather.",
    29: "Shriveled Eye Clan goblins are running at the characters with glowing maggots strapped to their backs. These mag- gots explode for 2d6 damage to all in 10’ radius.",
    33: "2d4 slaves that escaped from a mine and are attempting to get to the civilized territories.",
    35: "Gigantic roving slug with ramshackle fort of Shriveled Eye clan goblins on its back.",
    37: "2d8 humans- their skin is shriveled and clumps of rock pierce their flesh. Their eyes are sunken in and black ichor is leaking from their mouths.",
    38: "Tribe of 2d5 stone giants. They may be peaceful, or they may want to bludgeon tiny creatures to death…",
    41: "A small band of 3d3 Black Guard of Abhorrent Action and 2 Murder Machines in search of slaves who escaped with a haul of ore.",
    46: "Orc warband riding on the backs of mammoth abominations.",
    48: "Earth elemental with large calcified protrusions that jut out like serrated blades. Seems to be protecting a small wooden box.",
    49: "1d4 Rabid Ravens wish to bestow the characters with prophecy… if their minds can withstand the assault.",
    53: "Patches of sentient barbed grass lying in wait for fresh meat.",
    55: "1d3 mature brain grubs.",
    58: "Large egg sack filled with squirming larva. A successful Int check reveals they are immature brain grubs.",
    59: "A demon performing a ritual at the altar of the Heathen Below. Around the base of the altar are 2d10 chained and naked women.",
    60: "A fire beetle hive. The hive is made of rock and mud and shaped like the face of a screaming human. 10+3d3 fire beetles always present.",
    63: "The Black Queen’s Skeletal Gun Runners en route to deliver a shipment of wheellock weaponry to Klind in the Blighted Sands.",
    64: "Shriveled Eye Clan goblins riding on the back of a stone giant. The giant is gaunt, with hooks on his eyes and mouth, forcing them open.",
    67: "A shimmering cloud. Walking through it causes one of the character’s worst nightmares to manifest in the material plane.",
    71: "Bizarre mound of flesh with one thousand eyes, mouths, arms, and legs.",
    72: "Small sentient rockmen that are proud keepers of a mystic item called “The Resonance Key”.",
    74: "The remains of an ancient drake. It will animate and attack any who get too close.",
    77: "Orc wizard with 2d10 abomination Shriveled Eye Clan goblins.",
    81: "Swarm of flying purple locusts blot out the sky.",
    83: "Miners from Fairweather are trying to establish a small outpost, while fighting off interlopers from the Floating Island of Terror.",
    84: "Polymorph magical trap. If characters trigger it use spell description as if 24-25 was rolled on the spellcheck in DCC (pg 243).",
    85: "Klind, orc, and Eisenbar troops are engaged in a three-way battle.",
    87: "A Demon Lord is forcing slaves to build him a grand keep in the wastes.",
    88: "A herd of 3d10 animals and 2d6 miners that have been mutated into terrible beastmen by Blood Madness caused by the Bleeding Mountain that Pierced the Sky.",
    92: "Swarm of small stinging insects that cause a person to swell up terribly and leak orange fluid when bitten.",
    94: "Chameleon ooze lurking near party.",
    95: "Village of small lizard-beings. Their needle teeth drip with saliva and their red eyes seem to glow, even at night.",
    96: "Community of 3d3 friendly stone giants. These giants left the Mountains that Crawl in search of a new life.",
    97: "A gargantuan brain grub that is retching prismatic-colored fluids. These can be bottled up and used in alchemical concoctions. Eventually the brain grub explodes, revealing a physical manifestation of the Corpulent One.",
    98: "A tattered and torn camp. There are several skeletons. The skeletal structure and clothing matches that of the characters.",
    99: "Caravan of traders heading from Klind to the civilized territories.",
    100: "A manifestation of the Heathen Below lumbers across the land; non-believers will be smote and struck from existence.",
}
