land_of_perpetual_stone_and_mire_lay = {
    1: "Barren wasteland, cracked dry ground, with patches of barbed grass.",
    16: "Ancient cemetery of a long-forgotten kingdom. Several small crypts line a path to a giant mausoleum made of marble and gold.",
    18: "Area of petrified trees, while in area no sound can be heard. Spells are unable to be cast, and the divine is not felt.",
    21: "Horrible altar to long-forgotten god (use Ancient and Forgotten Demigod Table, pg 224).",
    26: "Massive mound that is a physical wound of Hubris. It steadily trickles hot acidic blood, and stinking pus bursts out every 1d6 hours. All creatures in a 1 mile radius become sickened when this occurs (no save).",
    28: "A gigantic petrified tree that has become a tree fort for several members of the Cult of the Molted Raven. They caw and flap their faux-wings that are made from fabric and glued on bird feathers and jump out of the tree and attempt to fly, failing horribly.",
    30: "Field of cracked and jagged glass that bursts from the ground. 20% chance that looking through the glass will tear open reality and transport the viewer to another plane of existence for 1d4 days (use the Planes of Hubris Table, pg 239).",
    31: "Grove of twisted petrified trees with over-large human faces frozen in expressions of utter agony that whisper the secrets of the characters as they pass.",
    33: "Large gnarled tree with dead humanoids and animals that have been gutted and left impaled on the thick branches.",
    35: "Ancient swirling mist that contains the knowledge of years past. Those who remain in it for an hour gain +2 Int (Max of 20), but also incur one minor corruption.",
    36: "Dehydrated carapace of a gargantuan maggot. 2d6 Shriveled Eye Clan goblins have made this their home.",
    37: "Huge statue of a brooding head. On top of the head are 2d4 Rabid Ravens. Their eyes are rolling in their sockets as their terrible garbled cawing fills the air.",
    41: "Abandoned orc camp. Tattered tents made of tanned human flesh, large rotted and mutated bodies litter the ground.  In the center of the camp a cauldron containing some of the alchemical substance of the orcs still steams and bubbles.",
    42: "A hastily abandoned mining camp. The camp is overrun by: Roll 1d4- 1) infected villagers; 2) giant rodents; 3) Shriveled Eye Clan goblins; 4) swarms of parasitic insects.",
    46: "Large tar pit (30’ deep). Anything that falls in sinks 1d3’ per round. DC 20 Strength check to get out.",
    51: "Active mine maintained by a small group of guards that bully and lord over slaves and indentured-servants.",
    56: "Orc fortress built of the still-living flesh of thousands of creatures.",
    58: "Small group of explorers from: Roll 1d4- 1) Fairweather; 2) Shadowfall; 3) Eisenbar; 4) Klind.",
    61: "50’ discarded smoke stack from the Floating Island of Terror. An old man lives inside the cavernous cylindrical structure.",
    63: "Keep of the evil wizard Iboz. Constructed out of white marble, it resembles the upper body of the wizard.",
    64: "Orc incubation structure. Looks like a gigantic hive, like that of a wasp, but constructed from the flesh of hundreds of creatures. Humanoids and creatures trapped inside the structure can be seen gestating and becoming warped hideous abominations.",
    66: "Active Klind enclave capturing various species of life to experiment on back in their kingdom. There are always 3d10+10 Klind and 100 slaves present.",
    68: "Abandoned Eisenbar paladin camp. Some very useful supplies were left behind.",
    69: "Huge black pit. Heat and shimmering gasses waft up the large hole. Glittering gems can be seen along the rock face.",
    72: "Mine that is heavily guarded by several Black Guards of Abhorrent Action and Murder Machines. The miners are carrying out crates of faintly glowing green rocks.",
    75: "Geyser field erupting, sending jets of hot, sulfuric water and globs of yellow slime into the air.",
    78: "Huge swarm of Rabid Ravens blot out the sun. The concentration of their prophecy causes a void to open in the sky. Any character that looks into the center of the void catches a glimpse of future times and gains +1d3 Luck, but this vision of the future has a cost to their psyche and they lose 2d2 Personality.",
    79: "Cave of obsidian that is home to the Cult of the Molted Raven. There are 4d6+3 members present.",
    80: "River with water flowing backwards. The water is full of skeletal flying fish. Anyone who submerges themselves in the water ages 1d10 years. Drinking the water ages the person 3d10 years. If they die due to aging, they become a sentient skeletal wanderer.",
    81: "An ancient tower covered in life-leeching vines. The tower is the prison of an ancient primordial demi-god of hunger.",
    82: "Village of exiled and hunted mutants. They are outright mistrusting of outsiders and non-mutants. Any character able to cast arcane spells feels a draw towards the largest structure in the village, the manor house. Inside it is a golden statuette that vibrates in their hands when held and whispers in their mind.",
    84: "Long abandoned village constructed of bland grey stone. The buildings are of a bizarre and almost incomprehensible architecture, with sharp, strange corners and heights that seem to make the living space uninhabitable. In the basement of one house are 2d2 spirits trapped in limbo. They are playing chess and glad for new company.",
    85: "Raised dais with an altar in the middle. The statue is of a creature that has the head of a man with a halo of a thousand screaming heads, the eyes bleeding acidic blood, and gasping mouths all over its body. At its feet are 2d6 crazed fanatics.",
    86: "A fetid bog that has a green haze that wafts lazily through the brambles and gnarled trees. In the middle of the bog is a gigantic anthropomorphic frog statue that is weeping nasty smelling water from its eyes.",
    89: "The remains of a gigantic Murder Machine. Its parts are scattered over a 25’ radius. It looks to have exploded and sent shrapnel everywhere. Several dead bodies are around the area, killed by the chunks of flying metal.",
    90: "Klind fortress. A brutal and hideous ritual in honor of Set is in progress.",
    91: "A statue of eight people, each one climbing upwards out of the mouth of the other until the last one is screaming at the sky, a bird flying from their open mouth.",
    92: "Beautiful healthy tree in the middle of a stretch of wasteland. Produces amazing fruit of various colors: Roll 1d8- 1) Red- heals 1d4 HP; 2) Orange- grants thermavision for 2d4 days; 3) Black- Fort save DC 20 or die; 4) Blue- gain ability to breathe underwater for 2d4 days; 5) Yellow- completely rested as if slept for 8 hours; 6) Green- rejuvenates 1d3 years; 7) Purple- Int tests are made one step higher on the die ladder, but Personality tests are one step lower as your skin is now purple- lasts 1d3 days; 8) Grey- painfully grow calcified rock claws that do 1d4+1 damage. Lasts 2d5 hours. The tree has 2d4 fruit on it. Once picked the fruit will grow back (roll for color) in 30 days.",
    93: "A field of arms and legs that look as though they have been planted in the ground. The appendages wiggle and flail in desperation, when dug out there is nothing there. The appendages wither to dried husks and crumble to dust in 1d8 days.",
    94: "Deserted mine; several pieces of equipment are scattered over the ground. An ill wind blows from the shaft and an unsettling clicking noise is carried upon the draft.",
    97: "A Klind enclave that is under siege by a warband of orcs. Several Klind are being dunked into an alchemical bath.",
    98: "Mudflats that stretch for miles. While traversing them, all suffer extreme thirst that cannot be satiated until through the area. Many go mad before they ever get out.",
    99: "Three sculpted stone statues of powerfully-built men with brooding features. They are each sitting on differently crafted thrones. Their eyes seem to follow the characters wherever they move. For a price they will answer a question posed by a character. One will lie, one will tell the truth, and one will ask a question of their own that must be answered lest that person be cursed!",
    100: "Large tower with large telescope pointed towards the sky. Magical runes have been inscribed all along the tower's base.",
}
