encounters_blighted_sands = {
    1: "2d8 Klind slavers prowling the Blighted Sands, one is a cleric of Set (lvl 1d3).",
    11: "1d4 orcs and a giant snake abomination.",
    13: "Nest of large sand wasps, 2d4 wasps present at any time.",
    14: "Caravan of traveling merchants making their way from Klind to Shadowfall.",
    16: "Skeletal Runners of the Black Queen, making their way to Klind.",
    22: "A gigantic serpent that escaped control of a Klind priest has been wreaking havoc in the wastes.",
    25: "A water bear bursts from the sand and wants to snack on the characters.",
    26: "2d8 escaped slaves, covered in congealed blood and sand wander aimlessly in the wastes.",
    28: "The cursed mummy of a: Roll 1d6- 1) klind; 2) kenku; 3) water bear; 4) human; 5) goblin; 6) orc lingers around collapsed ruins, which houses the Squelching Wish of the Envious Winged Monkey. The powerful protections around the ruin cursed the poor creature to become a protector of this valuable treasure.",
    29: "Warband of 20+1d20 marauding orcs. They have a full siege weaponry and look to be heading towards the Klind capital.",
    33: "A ball-like shape of 100+2d100 dead bodies rolls along in the desert. Hidden in the center of this grotesque monster is a Necrotic Demon.",
    35: "Cave full of scorpions. Also full of 3+2d20 gems worth 25gp each. At any time there are 2d10 small scorpions, 1d6 medium scorpions, and 1d3 large scorpions. There are also 2d6 dead and half eaten carcasses at the cave entrance (half of which are animals, the other half are humanoids).",
    37: "Exiled Dreamer Upon High of the Temple of the Lucid Dreamers is levitating slightly above a painful looking rock.  Behind him is his keep which rests on the back of a massive earth elemental.",
    38: "2d6 Venomous Red Scales are prowling the desert in search of a kidnapped young initiate priestess.",
    41: "A caravan that is completely undamaged, but covered with a fine layer of sand. All the herd animals and people are dead, dehydrated, covered in spider webs, and small scurrying brown spiders.",
    46: "A 20’ high, roughly hewn stone face that likes to talk in riddles about each character’s past.",
    48: "The High Priest of Set, traveling the wastes looking for a suitable place to create a new tower for his serpentine god.  Accompanying him are 10 Venomous Red Scales, 200 troops, 1000 slaves, caravan of goods, animals, entertainers, nobles, merchants, and supplies.",
    49: "A desert troll sitting atop a sand dune eating a giant scorpion.",
    53: "1d3 giant lizards.",
    55: "1d6 klind fighting 1d10 orcs, also being attacked by 1 water bear.",
    58: "A blight hag rests atop a jagged outcropping of rocks, singing a song of death and decay. Any who listen to the words risk madness and mutation.",
    59: "Ritual of Set occurring in the dead of night in the wastes. A child of Set is born out of the womb of a tied-up slave, who dies during birth.",
    60: "Field of cactuses with sharp crystalline thorns.",
    63: "Elephant-like creatures with emaciated bodies, overlong trunks, on 25’ high spindly legs.",
    64: "Emissary from Fairweather on his way to Klind, under attack by 1d6 large desert spiders.",
    67: "2d20 troops from Eisenbar bringing the pain of Drallic the Flayer to the heathen and blasphemous Klind.",
    71: "30’ area of pulsating flesh with 2d8 bulbous mounds. Closer inspection of the mounds reveal fetuses with malformed body parts. These body parts will attempt to throttle any who dig them up.",
    72: "Whirlwind with lightning and large hail whipping through the wastes.",
    74: "3d6 Giant fire salamanders are attacking a Klind outpost.",
    77: "Orcs riding on corrupted moths dropping alchemical compounds that melt through flesh and rust metal.",
    81: "Fire beetles have made a hive in the carapace of water bear.",
    83: "A drake flies overhead, breathing flame and smoke on the characters.",
    84: "Sinkhole trap created by a giant sand wasp. Will sting and incapacitate any who fall into the hole. Eggs will be laid on the back of the target immediately and hatch in 1d3 days and begin eating target’s flesh.",
    85: "Caravan attempting to flee from the Slithering Peaks after having confiscated several of the deadly red asps from the holy mountains.",
    87: "2d30 gnoll slavers bringing in “cargo” from all over Hubris for trade with the Klind Empire",
    88: "Herder making his way to an oasis with his flock of giant beetles.",
    92: "What seems to be a massive sand dune is lumbering across the wastes. The dune is actually a gigantic sand turtle.  An old hermit lives on the creature’s back.",
    94: "Sentient inky black pool of malevolent intelligence that seeks to corrupt those who come near to its shore.  952d6 raiders setting up ambush on caravan approaching in the distance.",
    96: "Weathered and ancient book sitting on stone dais in the desert; pages are dripping in a disgusting substance (that fits chosen patron). Book contains the ritual of the patron bond spell (Judge’s choice).",
    98: "Raiders have unearthed an entrance to a catacomb. They are being slaughtered by 10’ necrotic beetles and scorpions.",
    99: "A group of 3d5 bald, blind, albino, half-human half-centipede creatures are laying eggs on the belly of a dead water bear.",
    100: "A powerful ritual by a group of klind priests and Sex Prophets brings forth a spectral manifestation of Set.",
}
