lay_sea = {
    1: "Expanse of red ocean stretching out for miles.",
    16: "Small island of volcanic rock with no vegetation growing.",
    18: "Small island of volcanic rock with small amounts of vegetation growing. 25% chance of interesting feature: Roll 1d4- 1) ruin; 2) altar; 3) cemetery; 4) monastery.",
    21: "Patch of shallows with reefs of vibrant purple and blue.",
    26: "Area of crosscurrent, bits of wood and other chunks of dead ships, and garbage float in this eddy. There is treasure to plunder for the daring…",
    28: "Thick orange mist that obscures vision and makes those who breathe it in sleepy.",
    30: "Large 70’ high spire thrusting up from the ocean. At the top is an intricately carved statue of Zxyldon.",
    31: "Island with an ancient and dilapidated lighthouse. The lighthouse is ran by the Heath family, nobles exiled from Fairweather for birthing an heir through the Ways of the Flesh.",
    33: "Patch of ocean that is black and thick as tar; it smells like crude. Bits of bone float just above and below the surface.",
    35: "A large island covered in lush green plants, trees, and vibrant flowers. Living on the island is a dryad and her druid lover. The island is actually Grylath, the offspring of the great Slathereth (pg 75).",
    36: "Large white rock with stripes of black winding throughout the stone. In the center of the rock is a carving of a screaming man, in his mouth is a keyhole.",
    37: "The water is super-heated and boiling. Steam and the smell of cooking fish fills the air.",
    41: "Small grouping of whirlpools. If a character looks into the eye of the whirlpool, they will see another plane of existence (use Planes of Hubris table, pg 239).",
    42: "The sea bubbles and churns. Every few minutes a large jet of water shoots 50’ high into the air.",
    46: "A small island of pure white sand. 2d4 marooned sailors are on the island after their merchant vessel was lost to the sea.",
    51: "The sky turns pitch black as a violent storm rages through the area. Thunder, lightning, hailstones, and rain. 25% chance for weird storm (i.e.- frogs, fire rain, locusts, marbles, etc.).",
    56: "Remains of an island that is now bits of jagged rocks and craggy fissures.",
    58: "Small island that has 2d6 statues that resemble deep ones.",
    61: "30% chance there is no wind in this area for 2d4 days. At the end of the duration there is 1 day of wind, then roll again.",
    63: "A metallic sphere built on jagged black girders rests just above the ocean.",
    64: "Fort made of wood and mud on a small island. 3d8 Blood Bay Pirates on island at any given time.",
    66: "There is a 20% chance that sound is silenced for 1d4 days when travelling through this area.",
    68: "Storm clouds with faces of the angry old gods of forgotten times. If given sufficient cause or offerings they will communicate with characters and offer aid or advice. To insult them is to bring forth their fury and wrath.",
    69: "An island of wood planks stitched together that floats upon the water. It is: Roll 1d4- 1) a small outpost for pirates; 2) an altar to Zxyldon; 3) a supply fort for merchants and the ships of the nations; 4) an abandoned outpost now occupied by deep ones.",
    72: "Underwater cove of flesh eating merpeople",
    75: "Underwater city of deep ones.",
    78: "Expansive cave underwater which holds the shrine to Zxyldon. Sufficient offering will allow the character(s) to speak to and be blessed by the sea god. However offense will cause the shrine to fill with acidic briny water.",
    79: "A collection of 3d100 dead and bloated bodies that have been lost to the sea. They are held together by seaweed, intestines, and crude rope. Home to Kallup, an obese water demon.",
    80: "Huge rock that eerily resembles a human skull. Cruel-looking featherless birds fly in and out of the eye sockets.",
    81: "A ship graveyard rests just below the water. The skeletons of the lost sailors grin up at those that are foolish enough to investigate.",
    82: "The waves are particularly violent in this area, making navigating the ship hard. The turbulent waves also slow down travel speed by 50%.",
    84: "A large idol of Zxyldon that juts out of the ocean. At any point there are 1d3 merpeople here and 2d3 deep ones;",
    60: "% chance that they are fighting.",
    85: "A massive glacier drifts lazily through the water. It is the prison for the old god of plague, who has been imprisoned for 20,000 years.",
    86: "Coral reef of sickly green hue. When a living creature gets to close the reef, it releases a toxic paralytic gas.",
    89: "The remains of the great kingdom of Hysteria. The island sank to the bottom of the sea over three millennia ago.",
    90: "A rainbow that leads to the east. If a ship follows it for 3 days it will lead to a small island with a house made of ivory and gold. Inside there are 3d100+1000 gp, one silver ring (magic) and one gold ring (cursed) in a cauldron.",
    91: "An underwater luminescent cave that leads to the kingdom of the merpeople.",
    92: "A volcanic fissure has superheated the water. There is a 20% chance that a demon from the Void will emerge from the fissure.",
    93: "The sky becomes reflective like a mirror. If a target attempts to touch the reflection it shatters, showing that they were all upside down and now come crashing down to the sea.",
    94: "Area of ocean of the deepest blue. The water is calm, the air fresh, and the animals healthy. Characters that sleep in this area must make a Will save or suffer effects of lunacy and paranoia for 1d6 days.",
    97: "An area with 2d4 cyclones of water moving around in destructive fury.",
    98: "The Dead Sea- all life that touches these waters dies. The veil between the spirit world and this one is thin, and ghosts and spirits walk freely, terrifying or helping those they come across.",
    99: "The observatory of Higel- A floating observatory that watches the heavens trying to determine the portents of the stars. Higel is an ancient, eccentric wizard that will only talk to those who bring him a bag of carrots and a lemon.",
    100: "The lost and terrible city of R’lyeh, where the great Cthulhu slumbers.",
}
