encounters_bogwood_swamp = {
    1: "Prospectors looking to find new claim.",
    11: "Roving band of 2d4 Ekrask scouts fighting twice that number of Vile Gut Clan goblins.",
    13: "An enraged troll fighting Vile Gut Clan goblins riding in a Hive Fortress on a gigantic crab.",
    14: "Prospectors that have just found a new ruin and are being attacked by something horrible that was locked within.",
    16: "1d6 Ekrask hunters. They are looking to trade goods and for help killing a terrible evil that has been lurking in the swamps.",
    22: "1d3 Bogwitches lurking just beneath the water. They will burst from the surface and attack the nearest character(s).",
    25: "2d4 Klind warriors, one is cleric of Set (level 1).",
    26: "2d2 giant vampire Bats.",
    28: "Spirit of a young girl who was drowned in the bog. She begs to be set free from her torment. If unable to help her after a few moments her true horrific visage will be revealed and she will attempt to kill the characters.",
    29: "Band of 2d6 Fire Breath Clan goblins. They are willing to be friendly to characters, but will attack if provoked.",
    33: "2d3 Fire Breath Clan goblins riding gigantic moths (or vampire bats).",
    35: "Cannibalistic demon-worshipping frogmen are sacrificing one of their brethren for their next meal. If disturbed before the first frog leg is pulled they become enraged and fight with abandon against the interlopers.",
    37: "Nasty hag with gigantic necrotic pustules, collecting ingredients for potions. For rare ingredients she will sell some of her potions. If provoked she will attack and then use the characters in her potions.",
    38: "2d6 deep ones wandering through the swamp (1d4 of them are riding giant eels).",
    41: "2d4 prospectors digging out lignite.",
    46: "2d4 friendly sentient mushrooms are being attacked and cut down by: Roll 1d5 - 1) prospectors; 2) Fire Breath Clan goblins; 3) Vile Gut Clan goblins; 4) a troll; 5) deep ones.",
    48: "A group of explorers that are suspended upside down in gigantic moth cocoons.",
    49: "2d4 crocodiles.",
    53: "A gigantic crocodile bursts from the water and latches its jaws on a character and attempts to drag them beneath the water.",
    55: "Assassin vine with several dead creatures entangled in it. It will attempt to grapple any creature that gets too close.",
    58: "Will-o-wisp attempting to guide travelers into quicksand trap (5’ deep) so it can suck out the character’s soul.",
    59: "Troll wandering blindly in pain. Its gut is being eaten by giant maggots and is constantly regenerating.",
    60: "1d3 Giant centipedes (15ft) scuttling over the remains of a fallen and rotted weeping willow.",
    63: "Living statue hungry for blood. Will not move if victim is looking right at it.",
    64: "Caravan under attack by: Roll 1d6 - 1) Klind; 2) Ekrask; 3) Vile Gut Clan goblins; 4) bogwitches; 5) a troll; 6) bandits.",
    67: "2d3 +1 troops from the East End Outpost scouting area looking for threats to the keep.",
    71: "Living spell the with the consciousness of a malicious wizard who was consumed by the casting.",
    72: "Bipedal mushroom men that have become twisted and evil from a terrible rotting disease.",
    74: "d4 bloated, fetid zombies. These are the cursed remains of prospectors who went missing 3d3 weeks ago from Stilt-town.",
    77: "2d8 Vile Gut Clan goblins riding on the back of wild boars.",
    81: "Leech swarm skimming water surface towards party.",
    83: "Toad Demon that has enslaved a boomtown and forced them to worship him.",
    84: "Three prospectors have been caught in the web of giant golden swamp spider",
    85: "Mutant outlaws: Roll 1d4 - 1) hostile; 2) friendly; 3) neutral; 4) have information vital to one of the players, but now roll d3 for attitude.",
    87: "Shambling Mound protecting a tree with shimmering golden leaves.",
    88: "Traders heading for Roll 1d4- 1) Fairweather; 2) East End Outpost; 3) Shadowfall; 4) Stilt-town. 20% chance they have something unique or rare. If rolled 10% or under they don’t realize it.",
    92: "Criminal running from bounty hunter from Roll 1d4- 1) Fairweather; 2) Shadowfall; 3) Eisenbar; 4) Floating Island of Terror.",
    94: "Mutated wizard who sees through eyeballs in his hands, looking for ruins said to hold amazing treasure and knowl- edge. Willing to split the treasure with the characters.",
    95: "Witch coven meeting in secret to perform powerful ritual to bring forth a dark one from the Void.",
    96: "3d8+3 deep ones torturing and skinning captured Ekrask and prospectors. The skins are being tanned and hardened to be used as armor.",
    98: "2d3 deep ones setting a trap to ensnare the characters.",
    99: "2d6 Malfactorium scouts from the Mountains that Crawl. There is a 15% chance that they ride on a gargantuan stone beetle.",
    100: "Vile Gut clan goblins warring with Fire Breath Clan goblins in epic goblin-style brawl.",
}
