lay_of_the_land_bogwood_swamp = {
    1: "Reedy and murky area of swamp filled with buzzing and biting insects.",
    16: "The swamp water becomes thick and hard to move through. Stopping for longer than a few moments causes the person to sink quickly. Depth: Roll 1d4-1) 3’; 2) 5’; 3) 10’; 4) 20’.",
    18: "Bubbles form on top of the water; when they burst the characters hear giggling and crying.",
    21: "Dense pack of huge fungal stalks. If kicked or hit a glittering dust falls from their caps. Characters now glow in the dark for 2d3 days or until the stuff is washed off.",
    26: "Grove of weeping willows, used by a sect of extremist druids as their outpost. They are preparing for war against the heathens that destroy nature.",
    28: "Tower built from the red rock of the Canyons of the Howling Red Rock. The tower is twisted and has many holes where bats and large insects fly in and out; the peak is carved with the face of an angry ancient-looking man.",
    30: "Area of swamp that is producing large amounts of methane. The air shimmers and is extremely flammable (6d6 damage to all in a 60’ radius if ignited). 3d4 Vile Gut Clan goblins are getting high off the fumes.",
    31: "Rotten, sagging, and oozing fungal stalks. There is a 1 in 6 chance that one will collapse on a character if they get too close, resulting in 1d6 damage and being covered in disgusting-smelling rotten vegetation.",
    33: "Small floating island of lignite. There are several piles of bones on top of the island. There is a 25% chance that this island is covered in mushrooms of an excellent taste. So yummy, but so full of a delayed unpleasantness; intense bloating and gas resulting in travel being slowed by 50% for the next 24 hours.",
    35: "Ancient stone tower sinking into bog.",
    36: "Grouping of four gargoyle statues, each facing towards one another and possessing a set of precious gems for eyes.",
    37: "Hot springs bubbling to the murky surface of the bog. Resting in it for 2 hours heals 2d6 HP, but dyes skin green for a # of days equal to twice the amount healed.",
    41: "Swirling whirlpool with giant red eye in the center.",
    42: "An abandoned boomtown. There is a 30% chance that there is useful equipment and supplies that have been left behind. 5% chance that an exceptional or magical item is there.",
    46: "Sink pit (2d10+10' deep) full of orange leeches that will latch on and begin to drain a target’s life essence (1 Stamina loss per round until freed).",
    51: "20’ tall yellow and gold fan fungus. Stewing the fungus in alchemical concoction for 3 hours will create: Roll 1d5-1) a tasty food additive; 2) a potion that will permanently dye the drinker's skin yellow; 3) a sleeping potion (DC 12 Fort save or sleep for 1 hour); 4) a thick solvent that dissolves even the strongest glue binding; 5) a noxious fluid that evaporates when exposed to air (DC 12 Fort save or become sickened for 2d4 rounds and suffer -2 to all rolls).",
    56: "Abandoned Vile Gut Clan goblin hive fortress that is built into a weeping willow.",
    58: "A Vile Gut Clan goblin hive fortress on the back of a gigantic crab roving through the swamp.",
    61: "Ancient hilltop graveyard from some forgotten boomtown.",
    63: "Ruins made with piercing blue stone which is ice cold to the touch and has frozen the ground around it.",
    64: "Gigantic weeping willow which is home to Rye, a dryad and her water elemental companion.",
    66: "Small Klind enclave- there are 3d3 Klind warriors here at any time. The leader is a level 2 cleric of Set.",
    68: "Abandoned Klind enclave. There is 40% chance of useful equipment here and a 20% chance of religious artifacts of Set.",
    69: "Small Ekrask hunting village- there are 3d4 Ekrask there at any time. They are neutral to the characters unless provoked.",
    72: "Prospecting camp that has been raided. Blood, body parts, and broken weaponry are strewn about the site.",
    75: "Active prospecting camp- there are 2d8 prospectors in the camp. They have a small amount of goods they are will- ing to trade or sell.",
    78: "Cave filled with pulsating orange crystals. 2d4 crystals can be harvested at any point. When added to an alchemist's potion it grants +1 to the Brew Potions roll.",
    79: "Cave with walls lined with human skins, home to the vicious swamp troll, Bralog.",
    80: "Ruins of pure alabaster that can only be seen under the moonlight.",
    81: "Swirling noxious fog fills the area, reducing vision by 75%. Those in the fog must succeed a DC 13 Fort save or contract Necrotic Rot (see Diseases, pg 233). The fog is issuing from the rotted, hollowed eye sockets of a dead little girl hanging from a weeping willow.",
    82: "Shivering fungus (roughly 2 ½ feet tall) covered in a glittering dust that has hallucinogenic properties.",
    84: "Village of cannibalistic demon-worshipping frogmen.",
    85: "Ruins with door shaped like gigantic skull. Doorknob is in nose cavity. Eyes fire lasers.",
    86: "Reed and fungal fortress of Fire Breath Clan goblins.",
    89: "Reed and fungal fortress of Fire Breath Clan goblins that has become rotten and diseased; their small bodies wrapped in strange silky cocoons.",
    90: "Pile of 30 bodies caught in an eddy.",
    91: "Skeleton of a gigantic reptile with purple steam issuing out of the eye sockets.",
    92: "Huge pendulum that swings back and forth on a massive weeping willow, which is home to an old witch. She will offer help to any who need it, for a price.",
    93: "Ancient ruins built in the shape of a squid. Horrific pale creatures resembling anthropomorphic squids with red eyes can be seen coming and going.",
    94: "A boomtown that has been taken over by deep ones (DCC, page 400). The villagers have all become corrupted half- man half-fish creatures. A large altar to Zxyldon (see The Sea That Runs Red territory, pg 130) has been constructed in the center of the boomtown.",
    97: "Abandoned Klind enclave that is now home to a fetid shadow creature. The dried husked remains of the Klind are scattered around the encampment.",
    98: "Field of sentient mushrooms. They have individual personalities but also a hive mindset. They hold secrets to an ancient ruin somewhere in the swamp and are willing to share the location in exchange for information to other parts of the world.",
    99: "Recently-attacked Ekrask camp now occupied by Vile Gut Clan goblins. There are 2d3 Ekrask being held prisoner and 3 times as many goblins.",
    100: "Over one hundred people have been turned into statues. Many are below the surface of the water.",
}
