encounters_great_plains = {
    1: "Bandits seeking easy money.",
    11: "Small band of Malfactorium seeking the Skull of the Crying Peasant for their queen.",
    13: "Gnoll slaving party (one is riding on the back of a Murder Machine).",
    14: "2d4+1 Vile Gut Clan goblins (2 are riding on giant wasps).",
    16: "Traders making their way to: Roll 1d4- 1) Fairweather; 2) Shadowfall; 3) Bogwood Swamp; 4) Glasturbury.",
    22: "2d8 Bugbears accompanied by a giant spider-demon possessing the head of a necrotic slimey-looking dog.",
    25: "2d8 Eisenbar paladins attacking heretics of their faith.",
    26: "1d4 rabid hyenas led by a gnoll shaman.",
    28: "Sentient twister that is lonely, but holds treasure in its eye.",
    29: "A vampire thrall and 3d4+3 militia from Shadowfall.",
    33: "Band of centaurs seeing vengeance for the murder of their leader, the Time Keeper.",
    35: "The Wretched attacking a caravan.",
    37: "Golem made of metal and spikes with bodies impaled on each. Some are still living.",
    38: "1d3 humans infected by the Metalphage.",
    41: "Refugees of a recently attacked village seeking help.",
    46: "Sorcerer falls out of the sky and dies. Holding strange glowing orb in his hands.",
    48: "1d4 dead victims of the Hangman’s Tree, all emit toxic miasma.",
    49: "3d4+3 guards from Fairweather. They are: Roll 1d6-1) fighting Eisenbar paladins; 2) camped out along the side of the road; 3) investigating rumors of a haunted keep that has appeared seemingly out of nowhere; 4) harassing a small avarian caravan; 5) dead and been torn apart by a vicious troll; 6) are looking for the characters.",
    53: "10 Skeletal Gun Runners from Floating Island of Terror delivering a shipment of guns and gunpowder to: 1d4- 1) Fairweather; 2) Shadowfall; 3) Bogwood; 4) Glasturbury.",
    55: "A raiding party of 5d3 gnolls riding in an armored wagon that was stolen from a group of Skeletal Gun Runners.",
    58: "A mutant eunuch carrying the living severed head of Apalas, a mistress of Ithis the Bulge. She was sacrificed to satisfy the needs of the Barking Moon, an ill omen of lunacy and starvation.",
    59: "Stone giant infected with Metalphage.",
    60: "Sorcerer making a deal with a small ice memphit with 4 heads.",
    63: "Hunters of the Court of Delirium searching for Wretched.",
    64: "Farmers about to burn someone they believe to be possessed.",
    67: "1d4+1 troops from Vigilance Keep.",
    71: "Royal envoy of Fairweather headed to Shadowfall.",
    72: "Earth elemental wandering around and melding boulders together to form a structure.",
    74: "2d4 ghouls hunting the characters.",
    77: "Eisenbar paladins seeking the characters for: Odd) help with a problem beyond their ken; Even) to cleanse the char- acters by pain and fire for their perversions.",
    81: "Swarm of biting flies. Chance characters become infected with larva.",
    83: "A strange creature who claims to be from a different world called the Charred Planet.",
    84: "A strange, otherworldly consciousness that guards the door to an ethereal library.",
    85: "2d4 Mutant outlaws. They are: Odd) hostile; Even) friendly.",
    87: "Necromancer with 1d4 zombies, 1d4 skeletons, and 1 ghoul.",
    88: "Exiled fae offering passage through the Weeping Forest of Forgotten Memories to anyone who can offer him a bottled baby’s laugh.",
    92: "Small community of mutants. Always 5d4+3 present.",
    94: "A man sitting on a boulder, smiling. Says he’s been waiting for the characters for 1d100 years.",
    95: "A beastman seeks protection from his own kind.",
    96: "Burned bodies tied to stakes. Stomachs are bloated with necrotic grubs.",
    98: "An emissary of the Spider Goddess descends from the sky on a thick web, offering parlay with the characters.",
    99: "Small village of children. They were once adults, but sold their emotions to a demon to remain forever young.",
    100: "A Witch coven has just finished a dark ritual that has brought forth the physical manifestation of their patron. The physical being of the patron is weak and frail, so it is placed in the womb of a cow. The patron will gestate for 3d3 months and then burst from the animal in a spray of blood, smoke and acid, fully formed and ready to bring forth their will to Hubris.",
}
