lay_great_plains = {
    1: "Rolling plains of grass, farmlands, grey mud, and thorns.",
    16: "Area of briers that drip blood.",
    18: "Vineyard with grapes that have the faces of humans, young or old. The grapes scream when they are squeezed. Those that drink the wine are flooded with euphoric memories that are not their own. This effect lasts 10 min per drink.",
    21: "Rocky hills with shrubs. In the morning a steaming fog rises off the ground. By the evening everything up to 4’ high is encased in a 2” thick layer of ice, regardless of the time of year.",
    26: "Plantation displaying a hideous level of opulence with slaves out in the fields working in the worst of conditions.",
    28: "Tattered remains of a farmstead, crops overgrown with razor grass, thorns, and weeds.",
    30: "A thick mist that makes it hard to breathe for any who are in the area. Peering into the mists causes the person to see all those that have died, in various states of decay, flitting in and out of reality.",
    31: "Abandoned fort of: Roll 1d6- 1) Eisenbar; 2) Fairweather; 3) Shadowfall; 4) unknown long-forgotten empire; 5) goblin; 6) Klind.",
    33: "Gnoll slaver camp. There are always 3d6+3 gnolls and 2d10+10 slaves present.",
    35: "Entrance to a Malfactorium underground stronghold. They are tunneling through the earth towards: Roll 1d3- 1) Eisenbar; 2) Fairweather; 3) Shadowfall.",
    36: "An orc warband attacking a settlement. They are using a gargantuan slug abomination to destroy the settlement’s keep.",
    37: "Several Wretched and savage beastmen are dancing around a screaming emerald green fire.",
    41: " Hangman’s Tree moving across the plains: Roll 1d4- 1) sneaks up on group making camp; 2) seen in the distance; 3) people fighting at its base; 4) someone being strung up.",
    42: "Giant statue of the Spider Goddess, surrounded by chanting bugbears that are completing a terrible ritual.",
    46: "Dry and brittle hillocks. These hillocks are actually an extensive hive of bees. Stepping on the hillocks causes them to crumble and break, releasing waves of angry bees that sting, bite and kill.",
    51: "Small undefended farming community with 3d6+3 people.",
    56: "Remains of unremarkable village. Exploration of the ruins reveals two dozen bodies wrapped in thick cocoons.",
    58: "Remains of unremarkable village. A large idol of Set can be found in the center of the floor of the church.",
    61: "A small settlement that has been burned down. Eisenbar Paladins are completing a rite to Drallic the Flayer.",
    63: "Ancient keep of a forgotten empire. Home to the self-proclaimed vampire queen, the “Red Lady.”",
    64: "Large obelisk erected to the Great Slumbering Monolith. There are always 2d4 priests present.",
    66: "Small mutant community (hostile to outsiders).",
    68: "Discarded metal tower of Floating Island of Terror.",
    69: "Area covered in strange glowing moss. Eating the moss causes: Roll 1d4- 1) hallucinations; 2) ability to float 1’ above the ground; 3) glowing in the dark; 4) a great night's sleep. Effects 1-3 last for 24 hours.",
    72: "Abandoned Eisenbar fort now occupied by Gnolls.",
    75: "Fairweather labor camp.",
    78: "Prison camp built entirely out of the bones of the guilty, reinforced in iron.",
    79: "Cave filled with Vile Gut Clan goblins. There are always 2d10+10 goblins present.",
    80: "Hideous alter with serpentine body, arms of a baby, and five hundred screaming heads.",
    81: "Asylum for the strange, insane, and mutated. Patients are cruelly treated.",
    82: "Lone inn for weary travelers. Painted in prismatic colors.",
    84: "Rip in the fabric of reality. Walking through the rip will transport the characters to: Roll 1d6- 1-2) another area of Hubris; 3-4) a new world; 5) different plane of existence (use Planes of Hubris table, pg 239); 6) into the Void.",
    85: "Fissures in the ground belching up yellow steam.",
    86: "Small tranquil pond. Magic does not function while near it. Should someone bathe in its waters, magic doesn’t work for 24 hours.",
    89: "Abandoned orchard with fruit that has interesting magical properties.",
    90: "An Eisenbar stronghold that has been taken over by orcs. The orcs are corrupting creatures with their strange alchemical potion: Roll 1d6- 1) Fire Breath Clan goblins; 2) gnolls; 3) humans; 4) bugbears; 5) a chimera; 6) dire bats.",
    91: "Bizarre upside-down pyramid with a door made of liquid gold.",
    92: "Crystalline cube with shadowed figures frozen inside. Upon closer inspection each character sees that the frozen figures are themselves.",
    93: "Bizarre metallic ruins that only emerge once every 100 years for 1d10 days.",
    94: "An ancient wooden fort occupied by 3d8+4 Fire Breath Clan goblins.",
    97: "A small stream that babbles softly. After soaking a blank piece of parchment in the stream for 1d5 days it will have a random spell transcribed on it: Roll 1d4- 1-3) wizard; 4) cleric.",
    98: "Cabin of the exiled prophet Crazed Tubble.",
    99: "Field of strange waving shrubs that are actually tentacles of man-eating plants.",
    100: "Gigantic 25’ tall Murder Machine that has been deactivated for a long time. Grass and vines have grown on and around the suit of armor.",
}
