# Generated by Django 3.2.9 on 2021-11-29 15:06

from django.db import migrations, models
import django.db.models.deletion
import markdownx.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Territory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('img_url', models.URLField(blank=True)),
                ('description', markdownx.models.MarkdownxField()),
            ],
        ),
        migrations.CreateModel(
            name='Rumor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='territories.location')),
            ],
        ),
        migrations.AddField(
            model_name='location',
            name='territory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='territories.territory'),
        ),
    ]
