# Generated by Django 3.2.9 on 2021-11-29 15:21

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('territories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='description',
            field=markdownx.models.MarkdownxField(default='oups'),
            preserve_default=False,
        ),
    ]
