blighted_sands = {
    1: "Large expanse of hot empty desert",
    16: "Oasis that has been corrupted by malignant presence. Any who drink from this water gain 1d3 mutations: Roll 1d6: 1-3) cosmetic mutation (pg 43); 4-5) power mutation (pg 44); 6) calamitous mutation (pg 49).",
    18: "Volcanic region, lava and geysers erupt sending sulfur and ash into the sky.",
    21: "Expanse of sand dunes that if watched closely seem to be rising up and down as if breathing.",
    26: "Long-forgotten mine of ancient empire. Holds unimagined wealth, ore, and horrors.",
    28: "A single magnolia tree in the midst of the desert. The white blossoms bring a calming effect to all who inhale their intoxicating scent.",
    30: "A field of grass and flowers. The flowers can be dried and ground up to make an extremely powerful hallucinogen.",
    31: "Ancient weathered statue of anthropomorphic elephant.",
    33: "Ruins with doorway that resembles a bloated toad.",
    35: "Whirlpool of sand, in the center is a single glowing rose.",
    36: "Sun-bleached skeleton of a gigantic snake.",
    37: "Field of colorful sand that swirls around in the wind to create beautiful pictures of the inner-most desire of any character that walks up to it.",
    41: "Stone slab shaped like a table. Skeletons are arranged on rocks, sitting as if at a tea party.",
    42: "The remains of an ancient town.",
    46: "Jagged rocks jut out of the sand for several hundred feet There is a 35% chance the area will have patches of quicksand, 25’ radius (3d10+10 ft deep).",
    51: "Klind enclave that is heavily fortified (2d16 slaves in area with 10+1d10 guards always present).",
    56: "Outcropping of rocks that stand about 10’ tall. Upon closer inspection each resembles one of the characters.",
    58: "A small oasis- 1d4 sprites guard this sacred land.",
    61: "A small oasis 2d4 bandits have claimed as home.",
    63: "Ruins made of a bright red sandstone, half buried in the sand.",
    64: "A stationary sandstorm, with flashes of lighting in the sky. A strange structure is barely visible through the rolling sands.",
    66: "Recently attacked Klind outpost, dead slaves, klind warriors, and orcs litter the area.",
    68: "Medium oasis with waterfall where the water is falling up.",
    69: "Small trading outpost of merchants from all over Hubris.",
    72: "Field of volcanic rock lined with obsidian.",
    75: "Field of sand that has been heat blasted into glass.",
    78: "Dank sinkhole. Walls are wet with mucus. A chittering noise echoes from the sinkhole's depths.",
    79: "Large depression in the sand. Healthy pine trees are growing out of the desert floor.",
    80: "The remains of a large stone crafted city, mostly buried in sand.",
    81: "Klind outpost overrun with orcs that they have heavily fortified. Air around it shimmers due to large vat of alchemical substance.",
    82: "3 mile area of wet sand that is a nesting field for water bears. The sand slows movement by ½ and there is a 30% chance per 100’ to fall into a sinkhole that is 3d10’ deep.",
    84: "Small village of exiled klind.",
    85: "Wall made of the heads of humanoids, each is in a state of decay, oozing blood, pus, or ichor. All are alive and willing to chat.",
    86: "Ancient temple to long forgotten god.",
    89: "Large wooden ship berthed in a huge sand dune.",
    90: "Area of land that severs the connection with the divine. Passing through causes a cleric to not be able to use spells and abilities for 1d3 days.",
    91: "Gigantic sculpted face, peering through the eyes shows a different location in Hubris, changes every 1d7 hours. Next to it is a huge hourglass counting down until change.",
    92: "20’ pool of thick tar. Standing in it for more than 1 min causes skin to become dyed permanently black; also melts metal instantly.",
    93: "Tomb of a forgotten civilization of giants that served gods from beyond the Void.",
    94: "Area where sand is black and white, all magic is 1) amplified (+5 to rolls); 2) dampened (-5 to rolls).",
    97: "Gnarled and twisted singing bush.",
    98: "Remains of a floating citadel that crashed into a small mountain.",
    99: "Wishing well in the middle of nowhere that is home to an angry fire genie. He is willing to grant a wish, but will ask a terrible price in return.",
    100: "Field of ooze- 40’ x 40’- travel is cut down to ¼ of original speed. Targets take 1d2 damage/rnd while in the area.",
}
