sea_encounters = {
    1: "Merchant ship sailing the seas. Roll for ship: Roll 1d5- 1) pirate; 2) Ekrask; 3) Klind; 4) Fairweather; 5) Undra",
    11: "2d3 man-o-Wars drifting in the ocean.",
    13: "Three sirens sitting on a rock of pure white, singing a bewitching song of unbearable beauty and lament.",
    14: "A small ship full of pirates from Blood Pirate Bay.",
    16: "A Klind Warship sailing towards the Bogwood Swamp to land an incursion force.",
    22: "A gigantic water elemental attacking a merchant ship.",
    25: "The horrific Ness! A 150’ long sea serpent with jagged teeth hard as diamonds and eyes that blaze with the fires of Hell.",
    26: "2d3 bizarre creatures from beyond the Unknown Void are moving through the air/water.",
    28: "The ghost ship of Jack the Rotter has begun following the characters' ship. The black flag raised high on its mast.",
    29: "A merchant ship accompanied by 2 Fairweather military vessels.",
    33: "A gorgeous muscular man is riding on a giant man-o-war and waves at the characters as he passes by.",
    35: "2d8 deep ones riding on the backs of large piranhas, all carry bows and have a single bottle of Alchemist’s Fire.",
    37: "Dire great white shark charging the character’s ship.",
    38: "3d6 electric eels swimming around a lone man adrift on a small raft.",
    41: "A ship is being attacked by 3d8 Deep Ones. Roll for ship: Roll 1d5- 1) pirate; 2) Ekrask; 3) Klind; 4) Fairweather; 5) Undra",
    46: "3d3 mermaids sitting on a rock. They beg, writhe, moan, and flaunt to ensnare a sailor's senses and encourage them to jump into the waters and swim to their doom.",
    48: "3d10 large bloodshot eyeballs with meaty tendrils fly through the sky.",
    49: "A mutated orca bursts from the water and begins flying through the air.",
    53: "A wrecked ship is sinking into the depths of the ocean. Bodies float on top of the waves while birds and fish feed on their corpses.",
    55: "Orc raiders have built a mobile ocean fort on back of a giant sea turtle which has been corrupted by their alchemical concoctions.",
    58: "A lone woman sits upon a rock in the middle of the sea. Her hair changes color every few seconds. She is crying and screaming, “I’m sorry! I’m sorry for what I’ve done!” and is clawing out her eyes.",
    59: "A red water elemental from the Sea That Runs Red pummels into the characters' ship.",
    60: "2d6 Ekrask hunters looking for a worthy hunt in the dangerous ocean.",
    63: "A single metallic vessel of foreign design appears on the horizon. Smoke is billowing from its smokestack and it is making good pace in catching up with the character’s ship.",
    64: "A small ship of pirates that have been stuck in a dead zone for 15 days. They are desperate for food and water. There is a 15% chance that the characters' vessel will become stuck in the same dead zone.",
    67: "A storm rips through the area: Roll 1d6- 1) hurricane; 2) thunder and lightning; 3) thunder and lightning, wind, and heavy wind/rain; 4) heavy rain; 5) gale winds; 6) freezing winds and snow (regardless of season).",
    71: "A swirling dark black cloud forms overhead, like the eye of a hurricane. Wind, lightning and thunder begin. After a moment a gigantic grey arm reaches down from the eye and attempts to snatch up the ship.",
    72: "A storm drake attacks the ship, looking for an easy meal or two.",
    74: "Wood-corroding jelly fish begin latching onto the hull of the ship!",
    77: "Savage lobstermen climb over the side of the ship and attack.",
    81: "A sky whale and its baby float by the ship for a few minutes before heading off into the distance.",
    83: "An Aoki apeman from the Unsettled Expanse (pg 139) is riding on the back of pterodactyl. Clutched in the Aoki apeman’s arms is a small baby with soft golden skin.",
    84: "A ship containing firearms from the Floating Island of Terror is headed to Undra for trade.",
    85: "A school of rainbow-colored fish begin swimming in strange patterns and formations. They are actually shaping out words. After the message is spelled out they die, float to the surface, and rot instantly.",
    87: "1’ long icicles start raining down on the ship. Each receives +1 to hit and does 2d3 damage.",
    88: "Deep ones have booby-trapped the remains of a ship using Alchemist’s Fire. The poor sailors who were captured by the deep ones were forced to each eat a man-o-war and are now suffering in agony. They are alive but can feel the creatures eating their insides. They writhe and beg for help. When a living target gets too close, the man-o-war's tendrils will burst from the host’s stomach in an attempt to ensnare another victim.",
    92: "Lobstermen wielding sea-snails that ooze a potent acid are attempting to board the ship.",
    94: "An extremely well-designed ship is sailing towards Undra. This ship belongs to Jalynia, a princess from the Great Spire (pg 84).",
    95: "1d4 pirate ships attempt to attack the characters' ship.",
    96: "The waters part beneath the ship and it descends/falls to the ocean floor.",
    97: "A thick fog manifests around the ship taking visibility to zero. When the fog parts the ship is on a blue ocean and all landmarks and stars do not align with known charts",
    98: "A cold snap flash freezes all the water around the ship, slowing movement by 90%.",
    99: "Tidus, the patron god of the merpeople, has decided that the pitiful creatures before him should stand trial for all the crimes against the sea.",
    100: "Zxyldon has been angered and rises up from the depths of the ocean to wreak havoc on the sea and land.",
}

