frozen_waste_encounters = {
    1: "Group of 2d4 Ingvar hunters: Roll 1d6- 1) making camp; 2) being attacked by 3d3 Icy Flesh Clan goblins; 3) being attacked by 1d2 frost giants; 4) hunting large game animal; 5) hunting horrific monster; 6) fighting a band of Skeletal Gun Runners.",
    11: "Icy Flesh Clan goblins building a snow fort using their thick mucus as mortar.",
    13: "Group of Skeletal Gun Runners making their way towards the Razorback Mountains.",
    14: "3d2 frost giants wandering the wastes looking for food and fresh victims.",
    16: "3d10 elk wandering the wastes. 15% chance a druid (lvl 1d3) is watching over them.",
    22: "Large predator looking for food: Roll 1d6- 1) polar bear; 2) grizzly bear; 3) 3d2 wolves; 4) wolverine; 5) snow leopard; 6) dire version of one of the creatures.",
    25: "Band of 2d6 snow gnolls looking for prospective food or slaves.",
    26: " Field of 3d30 snowmen: Roll 1d3- 1) golems commanded to harm all life; 2) golems that if offered enough gold will follow and protect characters; 3) village of sentient snowmen.",
    28: "An elder drake guarding a pile of treasure and a clutch of freshly laid eggs.",
    29: "Group of Ingvar hunters celebrating on the corpse of a dead frost giant.",
    33: "Yeti stalking the characters.",
    35: "Ice shards the size of a man’s fist begin plummeting from the sky.",
    37: "Gigantic ice worm bursts from the ground and hurtles towards the characters.",
    38: "An ice golem with the carved head of an eagle guards a small mound of snow with a golden door.",
    41: "Herd of 4d12 wooly mammoths wandering across the wastes.",
    46: "A dire snow leopard is attacking group of: Roll 1d4- 1) Ingvar farmers; 2) snow gnolls; 3) Icy Flesh Clan goblins; 4) pounces on the characters from a snow drift.  481d4 frost giants fighting 1d3 frost giants corrupted by the Metalphage",
    49: "3d4 Icy Flesh Clan goblins riding on the back of a wooly mammoth.",
    53: "Soldiers from Fairweather and hunters from Ingvar are building a new fort to protect against incursions from the east.",
    55: "A frost hag follows the characters. She wants to: Roll 1d4-1) cut out their eyes and make soup; 2) convince them to help her get the spleen of a golden yak to make her beautiful; 3) ask them to help kill her sister who is killing innocent children; 4) offer them each a delicious red apple.",
    58: "A gorgeous woman with soft glowing blonde hair, wearing only a simple silken shawl, giggles at the players and then runs away. She seems to be able to run atop the deep snow.",
    59: "A group of 3d12 with metal weapons, evil faces, and covered in blood splatters.",
    60: " Ingvar hunters on the backs of wooly mammoths heading to defend a small farming community from a frost giant raid.",
    63: " A demon sculpting a portal to the Void out of ice, snow and the intestines of the innocent.",
    64: "Smoking remains of a caravan. 50% chance there are goods of value. 20% chance 1d3 people remain alive, but injured.",
    67: "A caravan headed towards Ingvar. Has interesting news/rumors about: Roll 1d6- 1) Fairweather; 2) Shadowfall; 3) Bogwood; 4) The Roving Nibbleton; 5) Klind; 6) Eisenbar.",
    71: " An ice troll sits on a snow mound eating flesh off the back of a living maiden.",
    72: "A small child covered in soot and blood runs towards the characters. He says his nightmare came alive and ate his family.",
    74: "A black shadow is following the characters. No matter how close it gets, it remains a constant silhouette, save for a smiling mouth full of jagged, yellow teeth.",
    77: "A wizard is warming herself by standing near a summoned fire elemental.",
    81: " Freezing rain beings to fall. Shelter must be found before the characters freeze to death.",
    83: "A caravan of Skeletal Gun Runners from the Floating Island of Terror lies destroyed in the snow. There is a 40% chance that there are 1d4 pistols, 1d8 rifles, and 2d20 shots and powder in the wreckage. There is a 15% chance there is a locked box that contains a strange mechanical prosthetic arm with a buzzsaw hand.",
    84: "King Belking the Impaler is leading a large force of hunters towards the Crag to stop the frost giant raids once and for all.",
    85: "A crazed old prospector claims that he knows where the entrance to the tomb of the forgotten God of the Sun is located. He believes there are riches and wealth untold within the chambers.",
    87: "Mutant and bounty hunter, Cecil Plinth, has tracked his quarry, the fiendish mutant and mass-murderer Qualg the Bloody, to the Frozen Wastes.",
    88: "An ice troll is fighting 2d4 Ingvar hunters.",
    92: "A gelatinous cube has wandered up from a long-lost tomb and is now slowly making its way across the wastes.",
    94: "The frozen mummy of a small child wanders the wastes looking for revenge against the family that left her to die.",
    95: "A necromancer is about to complete a horrible ritual in 1d4 rounds and raise the corpses of the dead to be his undead servants. He is summoning: Roll 1d4- 1) an army of 3d8 frost giants; 2) an elder drake; 3) 4d20 Ingvar warriors; 4) 2d2 yeti.",
    96: "The homunculus of a powerful wizard is spying on the characters. If attacked the wizard will send 1d3 exploding homunculus in retaliation.",
    98: "A drake is swooping over an outpost, setting it ablaze.",
    99: "A crowd is seen in the distance. As the characters get closer it is revealed to be 5d100+100 zombies.",
    100: "The fallen angel Ophelia is leading a massive assault against Rewbald and then Ingvar itself.",
}
