frozen_lay_of_the_land = {
    1: "Flat icy plains that stretch on for miles. 20% chance to find corpses frozen in ice or snow drifts.",
    16: "Area of tundra full of small shrubs, razor grass, and black rocks.",
    18: "Massive snow drift with hollowed entrance. Growling can be heard issuing from within.",
    21: "15’ long crevice hidden in the snow. Targets suffer -4 to spotting it. Walking across it causes it to collapse. DC 14 Ref save or suffer 3d6 damage and fall 30’.",
    26: "Small, ill-equipped, Ingvar outpost. 3d2+1 inhabitants at any time.",
    28: "Well-fortified Ingvar outpost. 3d8+5 inhabitants at any time.",
    30: "25’ tall ice sculpture shaped like a warhammer.",
    31: "Mummified carcass of drake, half buried in a snow drift.",
    33: "3d3 geysers erupt from beneath the frozen surface. Any in area take 1d6 damage from the steam.",
    35: "Small area (roughly 10 acres) warmed by thermal pockets. Grass grows, animals thrive, and a small temple lies in the center of a large cluster of trees.",
    36: "Ancient temple built of shiny blue stone.",
    37: "An ancient burial ground of forgotten frost giant clans. The ice here never melts and is a deep blue hue. There is a 15% chance to find a relic or heirloom buried in the ice.",
    41: "Large hole in the ground with yellowish putrid steam wafting lazily towards the sky. This hole leads to the underdark and to the village of some small flightless man-bat creatures.",
    42: "Outcropping of 15’ high jagged ice spires.",
    46: "Small Ingvar village harvesting tubers and catching wild game.",
    51: "Small Ingvar village that was abandoned years ago. Now home to Icy Flesh Clan goblins. Network of grimy tunnels beneath the surface.",
    56: "Pool of steaming, welcoming water. It is actually a cursed lake; those who bathe in the waters risk freezing to death in mere moments.",
    58: "Mysterious wooly mammoth graveyard. It is rumored that all elderly mammoths attempt to make it to this area to die.",
    61: "Canyon 120’ deep, exposing a raging frothing river below.",
    63: "The sun and moon seem to be lower and larger in the sky than anywhere else in the wastes. While in this area day and night are twice as long.",
    64: "Field of people who have been frozen in place. Looks of anguish and horror mar their faces.",
    66: "Icy Flesh Clan goblins have built a small grouping of slimy hovel-like igloos. 15% chance of treasures hidden in the clumps of rotten flesh that fill the structures.",
    68: "Large stationary cyclone of ice, snow, and water. The sounds of screams are carried on the wind. Always 3d4 Icy Flesh Clan goblins present.",
    69: "Field of 3d30 snowmen. The heads of the snowman appear to follow the characters, but none can be glimpsed actually moving.",
    72: "Large chunk of glacier; inside lurk 2d3 frost giants.",
    75: "Rock formation gouged out by the movement of glaciers. Deep cave leads to the abandoned hideout of Ingvar outlaws, long killed by a dire polar bear.",
    78: "Massive moving glacier that is actually an ice elemental.",
    79: "Tower constructed of yellow rock which glows faintly in the sunlight. Carvings of the face of an angry sun god can be viewed when up close.",
    80: "Deep crater in the ground. Remnants of porous rock of foreign composition can be unearthed from beneath the snow.",
    81: "Field of pumpkins. All are warm to the touch.",
    82: "Quaint wooden hut in the middle of nowhere. Home to a small family of 5 and a dog (or so they appear).",
    84: "Field bathed in blood. Several mutilated bodies of Ingvar hunters and animals are scattered around. Lying here and there a few bodies of fallen frost giants.",
    85: "Intricately carved ice sculptures of 30 children in a circle holding hands. When the wind passes through them, you can hear singing.",
    86: "Small frozen lake. Several fish can be seen swimming around beneath the ice. 30% chance a human figure is seen beneath the ice. 50% chance that figure is alive.",
    89: "Abandoned outpost of Eisenbar. The Ingvar made it clear they will not tolerate them in the wastes.",
    90: "Large castle made of ice. Inside lurks the beautiful, yet terrifying witch Wicked Agatha.",
    91: "An area of trees and wild growth that is more in common with the Unsettled Expanse than the Frozen Wastes. Exploration will find a seed the size of a large bolder, vine-like tentacles plunging into the ground.",
    92: "Area is covered in thick mist, reduces visibility by 75%. There is a 30% chance of freezing rain in area. If the characters sleep in the area they will awake in the morning to sun, with a high of 23 degrees and a 35% chance of thunderstorms in the evening.",
    93: "Altar created to honor Ophelia, the fallen angel and queen of the frost giants. There are always 2d2 frost giants present.",
    94: "Small Ingvar farming community that lives on the fringes. Always 3d6 people, 1d3 hunters, and 4d4 livestock animals.",
    97: "Stone and gemstone palace buried 20’ beneath the ice.",
    98: "House made of gingerbread and frosting. Singing can be heard as candlelight dances merrily through the windows.",
    99: "20’ tall metallic cylinder crackling with electricity and emitting a soft humming. Metallic double doors are cracked open and a green gas wafts from the opening.",
    100: "Intricately designed snow crop circle. Any who spend over 1 hour examining the pattern begin to hear their name whispered on the wind, calling them to the north, towards the Necropolis.",
}
